### ISSUE TITLE
New CMakeLists.txt breaks existing usage

### ISSUE THREAD

**Issue by Ryan-rsm-McKenzie** [marzer/tomlplusplus#104]
## Environment
**toml++ version and/or commit hash:**  latest / 7bf8c03f7ac8e0c6f717bf946bf7d49edc6509ec

**Compiler:**  N/A

**C++ standard mode:**  N/A

**Target arch:**  N/A

**Library configuration overrides:**  N/A

**Relevant compilation flags:**  N/A

## Describe the bug
Your meson script writes the cmake target as `tomlplusplus`:
https://github.com/marzer/tomlplusplus/blob/7bf8c03f7ac8e0c6f717bf946bf7d49edc6509ec/meson.build#L532

However, the new native cmake integration writes the target as `tomlplusplus_tomlplusplus`:
https://github.com/marzer/tomlplusplus/blob/7bf8c03f7ac8e0c6f717bf946bf7d49edc6509ec/CMakeLists.txt#L16

This will break anyone's cmake files which were written for the targets generated by meson.

**Comment by marzer** [comment]
Ah, right. Gonna loop in @friendlyanon here, since the new CMake stuff was their work.

@friendlyanon, what's the rationale behind it being `tomlplusplus_tomlplusplus`? Why not simply `tomlplusplus`?

**Comment by friendlyanon** [comment]
This change doesn't break intended CMake usage. The project + target name concatenation avoids polluting the build tree when the project is vendored so the chances of name collision is minimal. The ALIAS target that is created on the next line has the same name as the one from the install interface and the `EXPORT_NAME` makes sure the project name prefix is gone from the installed target.

When linking to CMake projects, please always use the namespaced targets with `::` in the name, because CMake is able to issue early diagnostics when that target is not found instead of silently passing the `-l<tpyo'd target name>` equivalent. Yes, that can cause nasty surprises, this is why you should use the `::` targets.

**Comment by marzer** [comment]
> When linking to CMake targets, please always use the namespaced targets with :: in the name, because CMake is able to issue early diagnostics when that target is not found instead of silently passing the -l<tpyo'd target name> equivalent. Yes, that can cause nasty surprises, this is why you should use the :: targets.

@friendlyanon can you clarify if that advice is for me, or for people consuming the library? Remember that I know next to nothing about CMake; if your changes have broken things for Meson users, I have three choices:
- Fix things so they good for both Meson and CMake (which I lack the knowledge to do, or currently the time to learn)
- Change the CMake target to match the existing one (though you make a good case for the way you've done it)
- Advise existing users to 'tear the band-aid' off and update their builds

**Comment by friendlyanon** [comment]
I have the feeling that the subject of this issue is code similar to this:
```cmake
add_subdirectory(tomlplusplus)
target_link_libraries(target PRIVATE tomlplusplus)
```
which as I mentioned was never a good idea. It should have always been:
```cmake
add_subdirectory(tomlplusplus) # or find_package(tomlplusplus REQUIRED)
target_link_libraries(target PRIVATE tomlplusplus::tomlplusplus)
```
As you can see, when using the proper namespaced target name, usage is the same, regardless of how that target is made available.

**Comment by marzer** [comment]
Ah, I see. So you're saying that this will only be a breaking change for people with CMake scripts that were 'doing it wrong', so to speak.

**Comment by friendlyanon** [comment]
I quickly looked at what Conan generates, and it also only makes the proper namespaced target available:
```cmake
# contents of generated tomlplusplusTargets.cmake
if(NOT TARGET tomlplusplus::tomlplusplus)
    add_library(tomlplusplus::tomlplusplus INTERFACE IMPORTED)
endif()

# Load the debug and release library finders
get_filename_component(_DIR "${CMAKE_CURRENT_LIST_FILE}" PATH)
file(GLOB CONFIG_FILES "${_DIR}/tomlplusplusTarget-*.cmake")

foreach(f ${CONFIG_FILES})
    include(${f})
endforeach()
```

**Comment by friendlyanon** [comment]
Actually, now that I'm looking at the meson build files, I see that `configure_package_config_file` is referencing the now deleted `cmake/tomlplusplus.cmake.in`, which I thought was merely an artifact from the previous contributor, so this issue has a merit to it, it's just not addressing the real issue.

As a sidenote, CMake's `configure_package_config_file` was never necessary for most projects. It's really only useful for projects that have package components (think `find_package(Boost REQUIRED COMPONENTS system ...)`) and need some more logic in the config file besides just making the targets available.

I have no experience with Meson, so I'm not sure what files it generates, but if it works the same as CMake itself and it generates the `*Targets*.cmake` files, then copying the config file is enough.

**Comment by friendlyanon** [comment]
OK, I downloaded Meson and after a quick look it makes the config generation a pretty DIY problem. I just restored the config file that I accidentally deleted.

**Comment by marzer** [comment]
Ah. Thanks for investigating. @Ryan-rsm-McKenzie can you confirm that this works as expected for you?

**Comment by Ryan-rsm-McKenzie** [comment]
Alias targets are read only, and cannot be used as an argument for many commands, such as `target_compile_definitions` (of which toml++ has many). Changing the target's name does not break usage for people who are "doing it wrong", it breaks usage for people who need to modify the target itself.

**Comment by friendlyanon** [comment]
I'm curious what the actual code is that you claim this breaks.

**Comment by Ryan-rsm-McKenzie** [comment]
It's occurred to me that you can only modify targets built by your project (i.e. via `add_subdirectory`) which of course you couldn't do until just now. This works as expected.
