### ISSUE TITLE
Replacing Values in a `toml::array`

### ISSUE THREAD

**Issue by LebJe** [marzer/tomlplusplus#109]
**Is your feature request related to a problem? Please describe.**
It seems that there's no way to replace a value in a `toml::array`. Currently, I'm using this code:

```cpp
auto array = toml::array { 0, 1, 2, 3 };

if (array.get(0)) {
	array.erase(array.cbegin());
}

array.insert(array.cbegin(), 5);
```

**Describe the solution you'd like**
I would like a way to easily replace a value, something like `operator[]` in `std::vector`:

```cpp
auto stdVector = std::vector { 0, 1, 2, 3 };
stdVector[0] = 5;
```

**Additional context**
None

**Comment by marzer** [comment]
Thanks for the suggestion. I can't implement this as operator[] because of the polymorphic nature of the data (well, I can, but not in the current design, and it necessitates a bit rewrite), but I can implement it using a member function, e.g. `array::replace(iterator, value)`

**Comment by LebJe** [comment]
@marzer Thank you for the solution. I look forward to using `array::replace(iterator, value)` in the future.

**Comment by marzer** [comment]
@LebJe  If you're still interested in this feature I've pushed an implementation of it to the v3 branch.

I won't merge v3 into master for a while yet since there's more work to be done before I cook a new release, but I welcome you to try it before then. (Do note that the v3 branch will be a massive ABI break so I'm not promising it will just work out-of-the-box without requiring a code change or two)

**Comment by LebJe** [comment]
@marzer Thank you very much! I've tested some of the features in the `v3` branch (including `array::replace`) and they work perfectly!

**Comment by marzer** [comment]
@LebJe Awesome, good to hear.

Somewhat related: I happened to notice you have a couple TOML parser+serializer projects in other languages that use toml++ as the native backend, meaning you're probably more sensitive to API and ABI changes than most. I'll try to keep CHANGELOG.md as up-to-date and detailed as I possibly can so you can get out in front of those breaks early. Please let me know if you see something I've missed.
