### ISSUE TITLE
Including toml++ as a subproject

### ISSUE THREAD

**Issue by stuhlmeier** [marzer/tomlplusplus#11]
**Is your feature request related to a problem? Please describe.**
The Meson build file doesn't define a [dependency variable](https://mesonbuild.com/Dependencies.html#building-dependencies-as-subprojects) which makes it (as far as I can tell) difficult to use as a subproject (via [wraps](https://mesonbuild.com/Wrap-dependency-system-manual.html)) in an existing Meson project.

**Describe the solution you'd like**
From what I can gather from the documentation and [several](https://github.com/radareorg/radare2/blob/master/meson.build#L450) [other](https://github.com/CLIUtils/CLI11/blob/master/meson.build#L8) [libraries](https://github.com/randy408/libspng/blob/master/meson.build#L46) (to list a few), probably something like

```meson
tomlplusplus_dep = declare_dependency(
  include_directories : inc,
  version : meson.project_version(),
)
```

added at the end of `meson.build`. I admit I'm not entirely sure if this is the correct way of solving this, so I think an issue is more appropriate than a PR for now.

**Comment by stuhlmeier** [comment]
I worked around this with 

```meson
tomlplusplus_proj = subproject('tomlplusplus')
tomlplusplus_dep = declare_dependency(
    include_directories : tomlplusplus_proj.get_variable('inc')
)
```

but I now have the issue that including toml++ will cause it to try to run all tests (due to `subdir`) which fails immediately due to uninitialized Git submodules.

I am aware that (as mentioned in the readme) simply copying `toml.hpp` into a project will work, but manually including dependencies is not ideal, which is why I was hoping I could use wraps (which are intended to solve this issue.) Is there any way to fix this?

**Comment by marzer** [comment]
Hi @stuhlmeier, thanks for raising this. I have to admit I'm new to meson so I've likely made poor choices in the configuration. I'll have a look into this tomorrow and see what I can learn.

**Comment by marzer** [comment]
Apologies @stuhlmeier I didn't have time to look into this yesterday as I'd hoped. I'll try to follow-up on it during this week.

**Comment by shdnx** [comment]
I'd add that when I'm using toml++ as a subproject, I also don't want to have tests built, or have to deal with any additional external dependencies. I'd suggest either adding an option whether to build tests, or just not building them when `meson.is_subproject()`

**Comment by marzer** [comment]
@shdnx Yup you're exactly right, that's how it should work. I haven't been able to get back to this yet but if you have experience enough with meson to configure this better, I'd welcome a pull request! :)

**Comment by shdnx** [comment]
@marzer I have the changes ready, but I'm not sure how to create a pull request. I'm guessing I need to be a maintainer?

**Comment by marzer** [comment]
1. Fork the repo
2. Commit the changes on your fork
3. Make a pull request from your repo to mine

See here for details: https://help.github.com/en/desktop/contributing-to-projects/creating-a-pull-request

**Comment by marzer** [comment]
(though that is about GitHub Desktop specifically; you can make a pull request directly on the github website itself. The important part is the forking)

**Comment by shdnx** [comment]
Thank you! PR open: https://github.com/marzer/tomlplusplus/pull/14

**Comment by marzer** [comment]
@shdnx Thanks. My read of it is that BUILD_TESTS controls the tests regardless, even when it's not included as a subproject, is that correct? Ideally I'd like the tests to always build _unless_ it's being included as a subproject, in which case they should be opt-in.

**Comment by shdnx** [comment]
@marzer: good point, fixed: `BUILD_TESTS` is now a feature option, where the default value (`auto`) means "only if not a subproject"

**Comment by marzer** [comment]
Awesome work @shdnx! Thanks for your contribution.

**Comment by shdnx** [comment]
Thank you as well for this awesome library! :)

**Comment by marzer** [comment]
@shdnx glad you think so! Don't be afraid to contribute in future.

@stuhlmeier this LGTM, please let me know if there's something we've missed

**Comment by stuhlmeier** [comment]
I've taken a look at it, this is basically what I was thinking of but I unfortunately didn't have any time to get to this myself. It looks great, thank you @marzer @shdnx :)

No worries regarding Meson experience; I'm not very experienced myself which is why I submitted an issue instead of a PR; I wasn't too sure if my suggested change made any sense. Either way, the more I use it the more I find myself liking it :smile:
