### ISSUE TITLE
Redefinition error not being called

### ISSUE THREAD

**Issue by python36** [marzer/tomlplusplus#112]
## Environment
**toml++ version and/or commit hash:**
toml++ v2.5.0 037bfdd21f794d7212616d5e6f4f8baab543c472

**Compiler:**  
g++ (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0

**C++ standard mode:**  
17

**Target arch:**  
x86

**Library configuration overrides:**  

**Relevant compilation flags:**  

## Describe the bug
If the table was created earlier, then the redefinition error is not called

## Steps to reproduce (or a small repro code sample)
This is parsed without error:
```toml
[a.b.c.d]
  u = 6
[a]
  b.t = 8
[a.b]
  u = 0
```
Result:
```sh
[a.b]
t = 8
u = 0

    [a.b.c.d]
    u = 6
```
But this is with an error:
```toml
[a]
  b.t = 8
[a.b]
  u = 0
```
Result:
```sh
terminate called after throwing an instance of 'toml::v2::ex::parse_error'
  what():  Error while parsing table header: cannot redefine existing table 'a.b'
```

## Additional information
For example with tomli (Python):
```python
>>> tomli.loads("""
... [a.b.c.d]
... u = 6
... [a]
... b.t = 8
... [a.b]
... u = 0""")
Traceback (most recent call last):
...
tomli._parser.TOMLDecodeError: Can not declare ('a', 'b') twice (at line 6, column 5)
>>> tomli.loads("""[a]
... b.t = 8
... [a.b]
... u = 0""")
Traceback (most recent call last):
...
tomli._parser.TOMLDecodeError: Can not declare ('a', 'b') twice (at line 3, column 5)
```

**Comment by marzer** [comment]
Ah, interesting. Thanks for the report.
