### ISSUE TITLE
Support conversion from JSON to TOML?

### ISSUE THREAD

**Issue by cocomeow** [marzer/tomlplusplus#117]
**Is your feature request related to a problem? Please describe.**
I could get the JSON string from TOML table by `json_formatter`, but how can I read it again from JSON file and parse to TOML table. Please help me if i did not notice that on the document, thanks.

**Describe the solution you'd like**
JSON string or file should be supported by `parse` function?

**Additional context**

**Comment by marzer** [comment]
There's no built-in way to do this. The `json_formatter` exists for two reasons:
1. Despite being an arguably poor config format, JSON makes for a pretty good over-the-wire/storage serialization format (and indeed is used very commonly for those purposes), so going from TOML to JSON is a reasonable use-case
2. `toml++` already has the TOML parser and data-types so implementing the `json_formatter` was [super easy, barely an inconvenience](https://www.youtube.com/watch?v=OEaSnmf1JwY)  
  
For me to go in the other direction (i.e. from JSON to TOML) I'd need to implement and a complete JSON parser (plus all it's weird offshoots and dialects), which isn't something I'm willing to maintain. Fortunately I don't need to, though; C++ is spoiled for choice when it comes to JSON libs:
- https://github.com/nlohmann/json
- https://github.com/Tencent/rapidjson/
- https://github.com/open-source-parsers/jsoncpp
- probably quite a few more floating around
So if you need this functionality you could pair `toml++` with your JSON lib of choice and implement it yourself relatively easily.
