### ISSUE TITLE
parse_file fails with raw `char const*`

### ISSUE THREAD

**Issue by bjadamson** [marzer/tomlplusplus#12]
## Environment
**Compiler:**  
Clang 11

**C++ standard mode (e.g. 17, 20, 'latest'):**  
C++20

**Target arch (e.g. x64):**  
x64

**Exceptions enabled:**  
DISABLED

**Relevant `toml++` configuration customizations:**  
I use a proxy-header for including toml to help with warnings

```c++
#pragma once
#pragma GCC system_header
#pragma clang system_header

#include <toml++/toml.h>
```

**Relevant compilation flags:**  

> -Wall;-Werror;-Wextra;-Wmissing-field-initializers;-Wno-padded;-Wno-deprecated;-Wno-shadow-uncaptured-local;-fdiagnostics-color;-fcolor-diagnostics;-fcaret-diagnostics;-Wpedantic;-Weverything;-Wno-gnu-statement-expression;-Wno-reserved-id-macro;-Wno-c++98-compat;-Wno-c++98-compat-pedantic;-Wno-global-constructors;-Wno-newline-eof;-Wno-pragma-once-outside-header;-Wno-documentation;-Wno-documentation-unknown-command;-Wno-missing-prototypes;-Wswitch;-Wno-switch-enum;-Wno-ignored-attributes;-fno-inline;-fno-omit-frame-pointer;-fno-optimize-sibling-calls;-O0;-g0

## Describe the bug
Passing a raw `char const*` to parse_file fails to compile with the following error:

error: no matching function for call to 'parse_file'
  auto presult = toml::parse_file("levels/resources.toml");
                 ^~~~~~~~~~~~~~~~
../external/toml++/toml_parser.h:369:22: note: candidate template ignored: could not match 'basic_string_view<type-parameter-0-0, char_traits<type-parameter-0-0> >' against 'const char *'
        inline parse_result parse_file(std::basic_string_view<CHAR> file_path) TOML_MAY_THROW

## Additional information
I can work around this by manually wrapping my raw `char const*` with a std::string_view, but this code is shown working in the README.md file (which is why I filed it as a bug, not a feature request).

## Potential Fix
Here's the work-around I added to my local copy of toml++, maybe it will be helpful.

```
inline parse_result parse_file(char const* file_path) TOML_MAY_THROW
{
	auto ifs = std::basic_ifstream<char>{ file_path };
	return parse(
		ifs,
		std::string_view{ file_path, std::strlen(file_path) }
	);
}
```

**Comment by marzer** [comment]
Ah, the readme not using a string-view literal is an oversight on my part, but const char* ideally should be an acceptable overload, too. Thanks @bjadamson
