### ISSUE TITLE
uint64_t values cause compiler errors

### ISSUE THREAD

**Issue by HBaghdadi1995** [marzer/tomlplusplus#122]
## Environment
**toml++ version and/or commit hash:**  

Version: 2.6.0
Hash: 47216c8a73d77e7431ec536fb3e251aed06cc420

**Compiler:**  

MSVC v142 with 10.0.19041.0 for windows SDK

**C++ standard mode:**  

std:c++17

**Target arch:**  

x64

**Library configuration overrides:**  

N/A

**Relevant compilation flags:**  

N/A

## Describe the bug

Attempting to use `uint64_t` or `unsigned long long` returns the following compile-time error `Value initializers must be (or be promotable to) one of the TOML value types`

## Steps to reproduce (or a small repro code sample)

```
#include <toml++/toml.h>
#include <cstdint>

int main()
{
    uint64_t foo = 100;

    auto tbl = toml::table{{
        {"example", foo}
    }};
}
```

## Additional information

It looks like this error is caused by line 391 in common.h 
```
integer_value_limits<T>::max <= 9223372036854775807ULL;
```
This could be fixed by changing it to
```
integer_value_limits<T>::max <= 18446744073709551615ULL;
```

I'll see if I can create a PR for this issue.

**Comment by marzer** [comment]
> This could be fixed by changing it to <...>

The trait your referrring to is `is_losslessly_convertible_to_native`; changing the upper limit to the uint64_t range would be incorrect because TOML integers are 64-bit signed ints. Per [the spec](https://toml.io/en/v1.0.0#integer):

> Arbitrary 64-bit signed integers (from −2^63 to 2^63−1) should be accepted and handled losslessly. If an integer cannot be represented losslessly, an error must be thrown

So that means that C++ `uint64_t`'s are a bit tricky.

**Comment by HBaghdadi1995** [comment]
Okay thanks I see the issue now. I wasn't aware of this part of the toml specification.

And having looked more deeply into the code the result would be converted to int64_t in the end anyway, resullting in an integer_overflow.

That being said it would be nice to have a precompile flag to allow such a change to be made.

Thanks for your clarifacation I'll close this issue now.

**Comment by marzer** [comment]
Well that's a reasonable case, but I won't be changing my implementation. To do so would mean I'd have to add a separate value type for uint64 which would massively complicate things.

The spec mandates that I support 64 bit signed integers, so I do. It doesn't mandate that I support all integer types supported by the host platform, so I don't.

Besides, personally I think those other implementations are making a mistake. If someone used them to serialise some TOML containing, say, UINT64_MAX, then used a different lib on a different platform to read it, there's good chance it will fail. Adding room for this scenario would be a mistake IMO.

**Comment by pelletier** [comment]
@englercj Just to be clear about go-toml, we are still thinking it through, leaning towards not supporting uint64, for reasons similar to @marzer's.

**Comment by englercj** [comment]
Understood, it is of course your prerogative to decide what your library supports. I'm shoving my uint64's into strings currently, but will likely evolve towards my own parser/writer to support my use case. Thanks!
