### ISSUE TITLE
Memory leak due to gcc bug in v2.5.0

### ISSUE THREAD

**Issue by ronalabraham** [marzer/tomlplusplus#123]
## Environment
**toml++ version and/or commit hash:**  2.5.0

**Compiler:**  gcc 7.3.1 (but I believe all versions including the latest as of writing, 11.2)

**C++ standard mode:**  17

**Target arch:**  x64

**Library configuration overrides:**  `TOML_EXCEPTIONS` is 1

**Relevant compilation flags:**  None

## Describe the bug
There's a [gcc bug](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=66139) that causes a memory leak when an exception is thrown by `parse_value()` [here](https://github.com/marzer/tomlplusplus/blob/v2.5.0/include/toml%2B%2B/toml_parser.hpp#L2520), specifically because the destructor of the moved-to `key` is not called.

It looks like you've done a significant refactor for toml++ v3, so feel free to withdraw this if it's no longer an issue going forward.

## Additional information
We found this using [AddressSanitizer](https://github.com/google/sanitizers/wiki/AddressSanitizer). Does it make sense to incorporate this tool into your tests and CI?

Nice library! Looking forward to v3. 😃👍

**Comment by marzer** [comment]
Thanks for the report!

> It looks like you've done a significant refactor for toml++ v3, so feel free to withdraw this if it's no longer an issue going forward.

The parser has seen a significant refactor but I suspect this would still occur. Should be easy to fix though.

> We found this using AddressSanitizer. Does it make sense to incorporate this tool into your tests and CI?

Yup. Would also like to incorporate fuzzing at some point too.

> Nice library! Looking forward to v3

Thanks!

**Comment by marzer** [comment]
Also, _damn_. That GCC bug is pretty nasty. Kinda defeats the purpose of RAII.

**Comment by ronalabraham** [comment]
Yeah, it's pretty bad!

> I suspect this would still occur.

As far as I know (and maybe you already knew this), the bug only affects [aggregate initialization](https://en.cppreference.com/w/cpp/language/aggregate_initialization) ([`parsed_key_value_pair`](https://github.com/marzer/tomlplusplus/blob/v2.5.0/include/toml%2B%2B/toml_parser.hpp#L338-L342) in v2.5.0 is an example of an aggregate), so it's possible v3 might not have issues?

**Comment by marzer** [comment]
Oh, in that case it might be sorted in V3 after all. I changed the way strings are stored during parsing to eliminate some unnecessary copies, and in doing so removed a few of those helper aggregates. Next time I do toml++ work I'll have a look to confirm.

**Comment by marzer** [comment]
@ronalabraham Have just confirmed that it's fixed in v3. Thanks for letting me know about this! I've added ASan to the CI pipeline so hopefully I catch any regressions going forward.
