### ISSUE TITLE
CLI toml-test decoder

### ISSUE THREAD

**Issue by moorereason** [marzer/tomlplusplus#125]
**Is your feature request related to a problem? Please describe.**

I've been doing differential fuzzing against a few TOML decoders to see where they may handle inputs differently.  I would like to add `tomlplusplus` into the mix.

**Describe the solution you'd like**

Can `tomlplusplus` provide a CLI [`toml-test`](https://github.com/BurntSushi/toml-test) decoder?  The decoder takes a given TOML input via STDIN and outputs annotated JSON to STDOUT. Details are in the `toml-test` README.

**Additional context**

I've filed several bug reports in other projects and submitted new test cases to `toml-test` based upon this fuzzing.

Thanks for considering.

**Comment by marzer** [comment]
There's no toml-test decoder for toml++ currently, though my test suite consumes the test inputs from toml-test and generates C++ unit tests to validate using the test suite, e.g.: [https://github.com/marzer/tomlplusplus/blob/master/tests/conformance_burntsushi_valid.cpp](conformance_burntsushi_valid.cpp)

I update the conformance tests every time I do any work on the library so it's generally up-to-date.

"Why did I bother writing a C++ code generator and not just provide an encoder/decoder?", I hear you ask.

It made sense at the time. Third-party libs in C++ can be very annoying, with or without CMake and friends, so in the early days of toml++ this approach seemed easier. I am going to do another batch of toml++ work at some point in January so if I get time I'll revisit this.

**Comment by moorereason** [comment]
I'm not advocating that you stop generating unit tests.  Every(?) TOML package I've looked at generates local unit tests from the suite.  However, I've only found 5 packages that have a `toml-test` decoder implementation.

I find a `toml-test` decoder useful for differential fuzzing and submitting bug reports.  For example, I'm not a C++ programmer, but I can use a Go fuzzer to find and report bugs in a C++ decoder such as `toml11` (e.g. https://github.com/ToruNiina/toml11/issues/180 & https://github.com/ToruNiina/toml11/issues/181).  No C++ skills required! 😄

**Comment by marzer** [comment]
> I'm not advocating that you stop generating unit tests.

Oh, certainly. I didn't think you were. Apologies if I gave you that impression. Was just explaining why this repo does the seemingly-harder thing first, instead of the probably-easier-thing, heh.

I do certainly see the appeal. There's even a few tests I have to manually skip the code generation for because various C++ compilers don't like the in-code equivalent (e.g. GCC doesn't like whitespace after a trailing `\` in a string literal, and there's a few tests in `toml-test` that have those). I'll get around to it eventually, hopefully as part of the next release.

**Comment by marzer** [comment]
@moorereason I've implemented this in the [v3 branch](https://github.com/marzer/tomlplusplus/tree/v3) - see [v3/toml-test/README.md](https://github.com/marzer/tomlplusplus/blob/v3/toml-test/README.md) for setup info.

> Every(?) TOML package I've looked at generates local unit tests from the suite.

Just re-read this. How do you figure that? It certainly isn't true for the C++ TOML ecosystem. In fact toml++ is the only one that chose that route, as far as I can tell - the others (the still-maintained ones, at least) appear to have done the sensible in the first place thing and built toml-test decoders 😄 

In any case, toml++ has now joined the club and provided both an encoder and decoder for `toml-test`. Let me know how you get on with it.

**Comment by moorereason** [comment]
Sweet!  I'm trying to get through my existing corpus, and I'm getting a UTF-8 error on a case.

Given an input of `0="\u0800"`, the `tt_decoder` returns:

```
terminate called after throwing an instance of 'nlohmann::detail::type_error'
  what():  [json.exception.type_error.316] invalid UTF-8 byte at index 1: 0x80
```
Not sure what to do with that.

**Comment by marzer** [comment]
O_o

Are you using any custom tests that aren't currently a part of toml-test? I built it from master today and didn't experience that.

If so, can you share the toml/json files?

**Comment by moorereason** [comment]
> Are you using any custom tests that aren't currently a part of toml-test?

Yes, but I'm doing differential fuzzing against other `toml-test` decoder implementations via STDIN and comparing the results.

The TOML document in question is 10 characters long:
```
0="\u0800"
```
I've tested that input with 6 other decoders (in Go, C99, C++, Fortran, and Dart), and they all return valid and equal results.

**Comment by marzer** [comment]
Oh, right, fuzzing. Ok well I'll do some digging and see what's going on.

**Comment by marzer** [comment]
Ah, I see, it's the JSON library I'm using. Doesn't like the JSON generated from that snippet. Guess I need to RTFM to figure out why 😅

**Comment by marzer** [comment]
@moorereason That's fixed now in the v3 branch.

**Comment by marzer** [comment]
Oh, since you're adding new upstream tests to toml-test, you might like to know that the cause of the unicode crash in the JSON parser was actually caused by my lib converting the unicode scalar escape sequence `\u0800` into the wrong utf-8 byte sequence.

I had some unit tests in place for those conversions but they weren't broad enough. I've added a bunch more now: https://github.com/marzer/tomlplusplus/blob/b41e12f7362c46d18bceeda3455d50a059e75a52/tests/user_feedback.cpp#L196 - might be worth adding a similar set to toml-test
