### ISSUE TITLE
Truncate fractional time precision

### ISSUE THREAD

**Issue by moorereason** [marzer/tomlplusplus#127]
## Environment
**toml++ version and/or commit hash:**
v3 f3bd22bff4cba3e1133bbd7613f75a7331d2289f

**Compiler:**
gcc 11.1.0

**C++ standard mode:**
c++20

**Target arch:**
linux x86_64

**Library configuration overrides:**
n/a

**Relevant compilation flags:**  
`meson build_tt --buildtype=release -Dbuild_tt_encoder=true -Dbuild_tt_decoder=true -Dgenerate_cmake_config=false`

## Describe the bug
Given the TOML document `0=00:00:00.0000000000`, the parser returns an error:
```
$ echo "0=00:00:00.0000000000" | tt_decoder
Error while parsing time: fractional component exceeds maximum precision of 9
        (error occurred at line 1, column 21 of 'stdin')
```

## Steps to reproduce
Compile toml-test decoder and use the following on the command-line:
```
echo "0=00:00:00.0000000000" | tt_decoder
```

## Additional Information

This may be an implementation detail that should be ignored, but I'm reporting it anyway.  I expected the precision to be truncated instead of seeing an error.

The TOML spec:

> Millisecond precision is required. Further precision of fractional seconds is implementation-specific. If the value contains greater precision than the implementation can support, the additional precision must be truncated, not rounded.

If this is the desired behavior, let me know.  Thanks

**Comment by marzer** [comment]
Ah, thanks for letting me know. Indeed the parser should be behaving per the spec here, not issuing a error.

**Comment by marzer** [comment]
Fixed in v3 :)
