### ISSUE TITLE
Inline tables should be immutable

### ISSUE THREAD

**Issue by moorereason** [marzer/tomlplusplus#131]
## Environment
**toml++ version and/or commit hash:**
v3 b41e12f7362c46d18bceeda3455d50a059e75a52

**Compiler:**
gcc 11.1.0

**C++ standard mode:**
c++20

**Target arch:**
linux x86_64

**Library configuration overrides:**
n/a

**Relevant compilation flags:**  
`meson build_tt --buildtype=release -Dbuild_tt_encoder=true -Dbuild_tt_decoder=true -Dgenerate_cmake_config=false`

## Describe the bug
The following TOML document should be invalid:
```
a={}
[a.b]  # INVALID
```

The TOML spec:

> Inline tables are fully self-contained and define all keys and sub-tables within them. Keys and sub-tables cannot be added outside the braces.

## Steps to reproduce (or a small repro code sample)
On Linux:
```
$ echo "a={}\n[a.b]" | tt_decoder
{"a":{"b":{}}}
```

## Additional information
I've submitted a PR to `toml-test` for this case: https://github.com/BurntSushi/toml-test/pull/109

Found while doing differential fuzzing against [go-toml](https://github.com/pelletier/go-toml).

**Comment by marzer** [comment]
Ah, this one is annoying. Initially this behaviour was correct, but was changed per a discussion on toml-lang/toml where others insisted I was incorrect to prohibit it. This was from before that snippet was added to the spec so I guess retroactively I was right all along hah

**Comment by marzer** [comment]
Fixed in v3, thanks!
