### ISSUE TITLE
Detect trailing bare carriage return in comment

### ISSUE THREAD

**Issue by moorereason** [marzer/tomlplusplus#132]
## The non-conforming TOML snippet
The following snippet isn't exactly accurate since I'm showing a carriage return control character as an escape sequence.
```toml
#\r
```

More explicitly as a hexdump:
```
$ echo -n "#\r" | hexdump -C
00000000  23 0d                                             |#.|
00000002
```

## What you expected
I expected this to be an invalid TOML document.

## What you got
It's parsed a valid input.

```
$ echo -n "#\r" | tt_decoder
{}
```

## Environment
**toml++ version and/or commit hash:**  
v3 7d3770df92ceeee7c9fe4c2b15d50b23a620ab28

## Any other useful information

A bare carriage return (`0x0d`) is not a valid whitespace or newline character within a comment.  It must be followed by a line feed (`0x0a`).  This issue only exists when it's followed by the EOF.  If any other character follows the carriage return, it's properly detected as invalid input.

I plan to submit a test case for this to `toml-test`.

Found while doing differential fuzzing against [`go-toml`](https://github.com/pelletier/go-toml).

**Comment by marzer** [comment]
Oh, this one's easy; I explicitly check for EOF after an `\r` and permissively accept it:

https://github.com/marzer/tomlplusplus/blob/7d3770df92ceeee7c9fe4c2b15d50b23a620ab28/include/toml%2B%2B/impl/parser.inl#L1160-L1161

I guess it's not so 'fine' after all :D

**Comment by marzer** [comment]
Fixed in v3, thanks!
