### ISSUE TITLE
Confusing error on overly large float

### ISSUE THREAD

**Issue by moorereason** [marzer/tomlplusplus#133]
## The Bug
Decoding an excessively large float yields a confusing error message:
```
$ echo "0=1000000000000000000000000000000000000000000000000000000000000000000000.0" | tt_decoder

Error while parsing floating-point: leading zeroes are prohibited
        (error occurred at line 1, column 4 of 'stdin')
```

## What you expected
I expected to see an error such as "exceeds maximum length" instead of the confusing "leading zeros" message.

Removing one zero from the integer side of the float gives a better error message:
```
$ echo "0=100000000000000000000000000000000000000000000000000000000000000000000.0" | tt_decoder

Error while parsing floating-point: exceeds maximum length of 64 characters
        (error occurred at line 1, column 67 of 'stdin')
```

## Environment
**toml++ version and/or commit hash:**  
v3 47241d003e58c38dcff8a9f513404a29fbfc306d

## Any other useful information
Found while doing differential fuzzing against [`go-toml`](https://github.com/pelletier/go-toml).

**Comment by marzer** [comment]
Ah, good find, thanks. I can probably fix this pretty easily just by rearranging the order in which those error states are evaluated.

(questionable how valuable it is in practice, though. I doubt any human would encounter this in a real config!)

**Comment by moorereason** [comment]
Add another zero and you get a different error message:
```
$ echo "0=10000000000000000000000000000000000000000000000000000000000000000000000.0" | tt_decoder

Error while parsing floating-point: expected decimal digit, saw '.'
        (error occurred at line 1, column 74 of 'stdin')
```

**Comment by marzer** [comment]
Fixed in v3, thanks!

This actually identified a few inconsistencies in how floats and ints were being parsed into stack buffers. All three cases should now parse OK. There's still an internal length limit that's quite long, but now if you hit it you'll get a better error message in all cases.
