### ISSUE TITLE
Detect overloaded integers

### ISSUE THREAD

**Issue by moorereason** [marzer/tomlplusplus#134]
## Environment
**toml++ version and/or commit hash:**  
v3 3f4a540ca6ccbe9dd7be484cf063364de54247e4

**Compiler:**  
gcc 11.1.0

**C++ standard mode:**  
C++20

**Target arch:**  
linux x86_64

## Describe the bug
After 3f4a540ca6ccbe9dd7be484cf063364de54247e4, integer parsing no longer catches overloaded values.

Before that commit:
```
$ echo "0=100000000000000000000" | tt_decoder

Error while parsing decimal integer: exceeds maximum length of 19 characters
        (error occurred at line 1, column 22 of 'stdin')
```

After that commit:
```
$ echo "0=100000000000000000000" | tt_decoder
{"0":{"type":"integer","value":"7766279631452241920"}}
```

## Additional information
Remove one zero from that int, and we get an error, as expected:
```
$ echo "0=10000000000000000000" | tt_decoder

Error while parsing decimal integer: '10000000000000000000' is not representable in 64 bits
        (error occurred at line 1, column 23 of 'stdin')
```

Found while doing differential fuzzing against `go-toml`.

**Comment by marzer** [comment]
Oh, fuck. Thanks.

**Comment by marzer** [comment]
Fixed in v3, thanks.

It should also now use the `"is not representable in 64 bits"` message instead of the less-useful `"exceeds maximum X characters"` one in more situations (the previous character limits were too low)
