### ISSUE TITLE
array::insert_at defined with TOML_API rather than TOML_EXTERNAL_LINKAGE

### ISSUE THREAD

**Issue by Azarael** [marzer/tomlplusplus#136]
## Environment
**toml++ version and/or commit hash:**  
v3 - commit hash 5c5abfd

**Compiler:**  
MSVC 2022

**C++ standard mode:**  
latest

**Target arch:**  
x64

**Library configuration overrides:**  
None.

**Relevant compilation flags:**  
None.

## Describe the bug
The definition of `array::insert_at` in array.inl is preceded by `TOML_API` rather than `TOML_EXTERNAL_LINKAGE` (inline) as the other functions in the file are. This is causing ODR violations in my project.

**Comment by marzer** [comment]
Good find, thanks for the report! Fixed in the master branch.

**Comment by marzer** [comment]
@Azarael It occurred to me that the reason you experienced this andI hadn't was the combination of `TOML_HEADER_ONLY` and including the library in multiple translation units. FYI you can improve your compile times by disabling `TOML_HEADER_ONLY` and defining `TOML_IMPLEMENTATION` in a single TU (ref: [Speeding up compilation](https://marzer.github.io/tomlplusplus/#mainpage-example-speed-up-compilation))

Having said that, I'm thankful you _did_ experience it, so I could fix it! 😄
