### ISSUE TITLE
how to get json string, directly instead of having to serializing into a stream first?

### ISSUE THREAD

**Issue by pkbehera** [marzer/tomlplusplus#137]
```
  auto pr = toml::parse_file(toml_file);
  if (pr) {
    stringstream ss;
    ss << toml::json_formatter(pr.table());
    auto json_str = ss.str(); 
  }
```
The above does work, but an API like `to_string()` would be much more useful. Does it exist?

**Comment by marzer** [comment]
Doesn't currently exist, but could be added.

> would be much more useful

It would be more useful _for you specifically_.

**Comment by pkbehera** [comment]
>> It would be more useful for you specifically.
sure and faster!

**Comment by marzer** [comment]
How would it be any faster? The formatters are all stream-based, so any implementation of this just do what you've done above, hidden in a function. It would be exactly the same speed 

Unless you're implying I should re-write formatters, in which case, no.

**Comment by pkbehera** [comment]
> Doesn't currently exist, but could be added.

and still closed?

**Comment by marzer** [comment]
Yes, I decided this feature would be far too niche to bother putting in the library itself. If you want a function to convert TOML to a JSON string, you can make a helper function in your own codebase.

**Comment by marzer** [comment]
@pkbehera look mate you can take your thumbs-down emoji and the rest of your attitude and fuck off. 

'm already giving you a way to convert TOML into JSON, which is more than you'll find in any of the other C++ TOML libraries.

Don't give me fucking shitty attitude because you have to do the last 10% of the work, you poor baby.
