### ISSUE TITLE
How to get a nlohmann/json object?

### ISSUE THREAD

**Issue by pkbehera** [marzer/tomlplusplus#138]
I see that this project is using [nlohmann/json ](https://github.com/nlohmann/json)

I am doing the following to get a `nlohmann/json `from my toml:

```
  auto pr = toml::parse_file(toml_file);
  if (pr) {
    stringstream ss;
    ss << toml::json_formatter(pr.table());
    return nlohmann::json::parse(ss);
  }
```
But this is serializing the json to a stream and then parsing the same again as a `nlohmann::json` object! An API to get a `nlohmann::json` would be **much faster**!

**Comment by marzer** [comment]
It's only using nlohmann/json in the toml-test encoder/decoder, not in anywhere in toml++ itself. Not even in the `json_formatter`; that is implemented internally without using any dependencies.

I'm not adding a massive dependency to every user of the library just for this.
