### ISSUE TITLE
License SVG licensing?

### ISSUE THREAD

**Issue by kevr** [marzer/tomlplusplus#139]
I liked your license badge, so I took it for my own project at https://gitlab.com/kevr2d2/taskpp and modified it for GPL2.

Is this okay, license-wise? Do I need to credit tomlplusplus for this asset?

Thanks and sorry for the silly question.

**Comment by marzer** [comment]
Sure thing, do whatever you want with it. It was procedurally-generated using shields.io so it's not exactly my 'work' anyways. If you want to credit someone, credit them :)

**Comment by kevr** [comment]
Ah okay, thanks bud! <3
