### ISSUE TITLE
TartanLlama/optional is no longer active, and has a git issue

### ISSUE THREAD

**Issue by j8r** [marzer/tomlplusplus#151]
(I've not followed the template because it is not a bug in this library)

## Context

I'm the maintainer of the [xemu Flatpak](https://github.com/flathub/app.xemu.xemu), which now uses this library.
At first, the tomlplusplus commit used was producing build errors due to referencing a no longer present `dox` submodule (https://github.com/mborgerson/xemu/pull/868).

That being fixed by using the current `master`, another issues emerged related to `cmake/tl-cmake`, a git module which is a single-file repository (sigh) referenced inside the [TartanLlama/optional's .gitmodules](https://github.com/TartanLlama/optional/blob/master/.gitmodules).
However, the path already exists as a regular directory, which results to an error `Failed to download sources: module xemu: Not a gitlink tree: cmake/tl-cmake.` when running `git ls-tree c28fcf74d207fc667c4ed3dbae4c251ea551c8c1 cmake/tl-cmake` (which Flatpak builder does).

## Solution

I wonder if this library is really needed as a gitmodule in this project by default, mainly because it is optional.
Also the user may have already this library present in his/her project if (s)he use it.

Several options exists:
- download it when necessary, and add the path to the project's `.gitignore`
- vendor the project - it is small and no longer active, it may be fine.

I personally prefer the first option.
We can also imagine having this library automatically downloaded when `TOML_OPTIONAL_TYPE` is set to `tl::optional`, and perhaps having a flag to disable this behavior.
Maybe letting the user download it on its own is fine at the end.

**Comment by marzer** [comment]
Ah, thanks for the report. You're right, it's not really needed as a submodule. The whole idea behind it is that testing with it enforces the use of the general std:: optional API, so the library should satisfy that interface. I can always incorporate that header directly into the library test files, though.

Thanks, I'll action this tomorrow.

**Comment by marzer** [comment]
All fixed @j8r. I decided to just stop testing with tloptional since it's not really my library's responsibility to test third-party code.
