### ISSUE TITLE
All enabling/disabling specific formatters

### ISSUE THREAD

**Issue by shenlebantongying** [marzer/tomlplusplus#158]
This is a TOML library bundled with two formatter of other formats. If I want to get rid of the others, I end up not having the formatter of the TOML itself. 

"Don't throw the baby out with the bathwater"?

Sorry for my tendency of "de-bloating".

```
#define TOML_ENABLE_FORMATTERS 0
````

**Comment by marzer** [comment]
Yeah, that's a good point. I could add formatter-specific options, `TOML_ENABLE_JSON_FORMATTER`, `TOML_ENABLE_YAML_FORMATTER`, et cetera.

Fortunately in the mean time I wouldn't be too worried about bloat; in my own bloat tests disabling _all_ of the formatters makes a practically negligble difference.

**Comment by shenlebantongying** [comment]
Thanks for the info. I was trying to figure out the overhead for those additional formatters.

**Comment by shenlebantongying** [comment]
Thanks!
