### ISSUE TITLE
[Help, and suggestion] Problem with replacing all keys, and provides somewhere for us for questions

### ISSUE THREAD

**Issue by laper32** [marzer/tomlplusplus#163]
**Is your feature request related to a problem? Please describe.**
When use the library, we may met many questions, or help needed.
I think it's better to provide somewhere to discuss these questions, or provide any help if needed.

**Describe the solution you'd like**
Reference nlohmann's json repo, they provide 'Discussion' section for us to solve questions what we met.

**Additional context**

Following parts is my own question:
I have a table:
```
[Base]
Derived = "OK"

[[fruits]]
NaMe = "apple"

[fruits.physical]
Color = "red"
Shape = "round"

[[fruits.varieties]]
Name = "red delicious"

[[fruits.varieties]]
NAME = "granny smith"

[[fruits]]
nAme = "banana"

[[fruits.varieties]]
namE = "plantain"
```
And here, not all keys are in lowercase.
Now I want to convert all of these keys into lowercase, aka:
```
[base]
derived = "OK"

[[fruits]]
name = "apple"

[fruits.physical]
color = "red"
shape = "round"

[[fruits.varieties]]
name = "red delicious"

[[fruits.varieties]]
name = "granny smith"

[[fruits]]
name = "banana"

[[fruits.varieties]]
name = "plantain"
```
This is my implementation:
```cpp
void _lower(toml::table& t)
{
	t.for_each(
		[&](auto& key, auto& v)
		{
			
			if (auto* this_t = v.as_table())
			{
				_lower(*this_t);
			}
			if (auto* this_a = v.as_array())
			{
				this_a->for_each(
					[](auto&& val)
					{
						if constexpr (toml::is_table<decltype(val)>)
						{
							_lower(val);
						}
					}
				);
			}

			std::string lower(key);
			boost::algorithm::to_lower(lower);
			if (lower != key)
			{
				t.emplace(lower, v);
				t.erase(key);
			}
		}
	);
}
```
But this throws the exception: `Exception thrown at 0x00007FF703D6D939 in main.exe: 0xC0000005: Access violation reading location 0xFFFFFFFFFFFFFFFF.`
I think this is due to when accessing somewhere, but retrieved nullptr. However, I have no idea how to solve it......

**Comment by marzer** [comment]
Hmmm, this is a tricky one! I'm testing that code now and I see the same behaviour, but it's not immediately obvious to me why. I'll have a look and let you know.

> Reference nlohmann's json repo, they provide 'Discussion' section for us to solve questions what we met.

I recently established a [gitter](https://gitter.im/marzer/tomlplusplus) for this repository. My repo isn't anywhere near as active as nlohmann::json so I think a full discussion board is probably a bit overkill at this stage ^_^

**Comment by laper32** [comment]
> Hmmm, this is a tricky one! I'm testing that code now and I see the same behaviour, but it's not immediately obvious to me why. I'll have a look into it and let you know.
> 
> > Reference nlohmann's json repo, they provide 'Discussion' section for us to solve questions what we met.
> 
> I recently established a [gitter](https://gitter.im/marzer/tomlplusplus) for this repository, so you're welcome to ask questions on there if you like. My repo isn't anywhere near as active as nlohmann::json so I think a full discussion board is probably a bit overkill at this stage ^_^

I have a assumption here, by reading the source code.
The table is derived from node, and using: `using map_type	 = std::map<toml::key, impl::node_ptr, std::less<>>;`
The node_ptr is: `using node_ptr = std::unique_ptr<node>;`
By those typedefs above, is it probably:
`t.insert(lower, v)` => Insert with lowercase key, but the `v` is still previous non-lowercase one.
`t.erase(k)` => erase previous non-lowercase key, and value.
However, the newly inserted one's value is same as previous one, thus caused the same issue.

**Comment by marzer** [comment]
I suspect the problem is actually because the keys of the internal map are being modified while it's being iterated over. If you modify it to instead work on a second temporary table and assign the result at the end it works OK:

```cpp
	static void lower(toml::table& t)
	{
		toml::table new_t;
		t.for_each(
			[&](auto& key, auto&& v)
			{
				if (auto* tbl = v.as_table())
				{
					lower(*tbl);
				}
				else if (auto* arr = v.as_array())
				{
					arr->for_each([](toml::table& val) { lower(val); });
				}

				std::string key_lowercase(key);
				boost::algorithm::to_lower(lower);
				new_t.emplace(toml::key{ std::move(key_lowercase) }, std::move(v));
			});
		t = std::move(new_t);
	}
```

**Comment by laper32** [comment]
Ah, in other words, we need somewhere to save the modified result?

**Comment by marzer** [comment]
Yeah, otherwise the map's internal iterators are being invalidated during the loop.

**Comment by laper32** [comment]
Thanks for help!
And this issue will be closed.
