### ISSUE TITLE
Assert in unique_ptr::operator*

### ISSUE THREAD

**Issue by ncaklovic** [marzer/tomlplusplus#169]
## Environment
TOML++ version 3.2.0

**Compiler:**  
GCC 10

**C++ standard mode:**  
C++ 17

**Library configuration overrides:**  
TOML_ENABLE_FORMATTERS 0
TOML_EXCEPTIONS 0

## Describe the bug
Assert in `unique_ptr::operator*`

## Steps to reproduce (or a small repro code sample)
Use value in TOML whih does not parse, like
```
[a]
b = [c"]

```
## Additional information
- `parser::parse_array()` calls `array::emplace_back()` even if `parse_value()` fails
- `array::emplace_back()` does `insert_at_back()` and  `return *elems_.back();` - which is dereferencing nullptr. 
- dereferencing nullptr is undefined behavior - MSVC lets it pass, but GCC (libstdcpp) has [proper assert](https://github.com/gcc-mirror/gcc/blob/b3048b6ffb126a4624f66bad713fe6d1dc6dc13d/libstdc%2B%2B-v3/include/bits/unique_ptr.h#L452).

The simplest fix probably would be something like https://github.com/marzer/tomlplusplus/commit/4a4bf1ebbc558cfc2ae315474dc19c9f3a34f4d9. I didn't do PR because I would expect that some of the tests running on GCC already found the problem.

**Comment by marzer** [comment]
Ah, yup, looks like `parse_array()` is assuming that `parse_value()` throws on failure, not taking into account exceptionless mode - a silly oversight on my part. Have pushed a fix to master.

Thanks for the report!
