### ISSUE TITLE
Need to include header <fstream> to call toml::parse_file

### ISSUE THREAD

**Issue by damondd** [marzer/tomlplusplus#17]
## Environment
**Compiler:**  
GCC 9.1

**C++ standard mode (e.g. 17, 20, 'latest'):**  
C++20

**Target arch (e.g. x64):**  
x64

**Exceptions enabled:**  
Default

**Relevant `toml++` configuration customizations:**  
Use header-only <toml.hpp> 

**Relevant compilation flags:**  
-std=gnu++2a -Wall -Wextra -Wno-unused-parameter -O3 -march=native

## Describe the bug
Follow the readme to parse a toml file:
```cpp
#include "toml.hpp"
auto config = toml::parse_file("config.toml");
```
which reports:
```
src/toml.hpp:5028:8: error: too many initializers for ‘std::basic_ifstream<char>’
 5028 |   auto ifs = std::basic_ifstream<Char>{ str };
```

## Additional information
Solved by adding:
```cpp
#include <fstream>
```

**Comment by marzer** [comment]
@damondd This is not a bug, but intended behaviour, and is explicitly noted in the documentation: https://marzer.github.io/tomlplusplus/#mainpage-example-parsing-files

The rationale is that the library doesn't include headers that users _might_ not use. If someone only ever calls `toml::parse` on strings or string_views, they need not be forced to pay the compilation overhead of including `<fstream>`.

I could make the documentation about it a bit more explicit, though.

**Comment by marzer** [comment]
Oh, the example in the README doesn't say it! I'll add that too.
