### ISSUE TITLE
Can we have coverage data of test cases?

### ISSUE THREAD

**Issue by jasmine-zhu** [marzer/tomlplusplus#176]
**Is your feature request related to a problem? Please describe.**

search the cmake files, we have no coverage flags in this project like the external project - `json`, we can not know, how much code lines we've tested.

**Describe the solution you'd like**

 pls add the coverage flags in the cmake system for this project.

**Additional context**

Thank you so much.

**Comment by marzer** [comment]
Also note that if you want automated coverage it would need to be done with meson, _not_ CMake. I don't use CMake for the CI system (and dislike CMake in general).

**Comment by jasmine-zhu** [comment]
> 

okay my mistake. So can we support coverage with meson?

**Comment by marzer** [comment]
> If you want to make a PR for this, sure.

**Comment by jasmine-zhu** [comment]
> > If you want to make a PR for this, sure. Otherwise I'm not going to bother.

Okay. I'll try.Thank you~

**Comment by marzer** [comment]
I should probably reiterate that all the public API's in the library are tested, and it passes the toml-test suite, as well as a few hundred more custom cases, so there'd be very little point at this stage. I'm probably not going to make any changes based on any coverage reports.

**Comment by jasmine-zhu** [comment]
yes. I've tried this testsuites.run very quickly and there are 333 for decode 99 for encode.
Just curious for the coverage rate.
by the way, I have two failed cases. it would be very thankful if you can help, I'm trying to figure it out at the meantime as well.
`FAIL valid/key/escapes
     decode TOML from encoder:
       toml: line 1: unexpected '=': key name appears blank

     input sent to parser-cmd:
       {
         "\n": {
           "type": "string",
           "value": "newline"
         },
         "\"": {
           "type": "string",
           "value": "just a quote"
         },
         "\"quoted\"": {
           "quote": {
             "type": "bool",
             "value": "true"
           }
         },
         "a.b": {
           "À": {}
         },
         "backsp\u0008\u0008": {},
         "À": {
           "type": "string",
           "value": "latin capital letter A with grave"
         }
       }

     output from parser-cmd (stdout):
       = 'newline'
       '"' = 'just a quote'
       'À' = 'latin capital letter A with grave'

       ['"quoted"']
       quote = true

       ['a.b'.'À']

       ["backsp\b\b"]

     want:
       "\n" = "newline"
       "\u00c0" = "latin capital letter A with grave"
       "\"" = "just a quote"

       ["backsp\b\b"]

       ["\"quoted\""]
       quote = true

       ["a.b"."\u00c0"]

FAIL valid/key/space
     decode TOML from encoder:
       toml: line 5 (last key "\" tbl \""): expected '.' or '=', but got 't' instead

     input sent to parser-cmd:
       {
         " c d ": {
           "type": "integer",
           "value": "2"
         },
         " tbl ": {
           "\ttab\ttab\t": {
             "type": "string",
             "value": "tab"
           }
         },
         "a b": {
           "type": "integer",
           "value": "1"
         }
       }

     output from parser-cmd (stdout):
       ' c d ' = 2
       'a b' = 1

       [' tbl ']
        tab     tab      = 'tab'

     want:
       # Keep whitespace inside quotes keys at all positions.
       "a b"   = 1
       " c d " = 2

       [ " tbl " ]
       "\ttab\ttab\t" = "tab"

toml-test [./toml-test/tt_encoder]: using embedded tests:  97 passed,  2 failed
`

**Comment by marzer** [comment]
My guess is the JSON library I'm using is butchering the inputs somehow; both of those tests are also part of toml++'s tests, and both pass:

- [valid/key/escapes](https://github.com/marzer/tomlplusplus/blob/master/tests/conformance_burntsushi_valid.cpp#L1783-L1804)
- [valid/key/space](https://github.com/marzer/tomlplusplus/blob/master/tests/conformance_burntsushi_valid.cpp#L1967-L1980)

(my test suite includes C++ versions of all of toml-test)

**Comment by eli-schwartz** [comment]
How far do you get by just configuring Meson with the core compiler option `-Db_coverage=true`, then running the testsuite + the builtin `ninja` targets Meson creates to run the coverage tools if they are detected as installed?

**Comment by marzer** [comment]
@eli-schwartz Good question; I have a vague memory of that being more difficult when I first investigated how coverage worked, but it seems quite simple. I'll try to find some time one weekend and look into it.

**Comment by arp242** [comment]
> My guess is the JSON library I'm using (or my toml-test encoder) is butchering the inputs somehow; both of those tests are also part of toml++'s tests, and both pass:
> 
>     * [valid/key/escapes](https://github.com/marzer/tomlplusplus/blob/master/tests/conformance_burntsushi_valid.cpp#L1783-L1804)
> 
>     * [valid/key/space](https://github.com/marzer/tomlplusplus/blob/master/tests/conformance_burntsushi_valid.cpp#L1967-L1980)
> 
> 
> (my test suite includes C++ versions of all of toml-test)

I'm not so sure that's the case; it's entirely possible I'm missing something here, but I did this:

	% cat test.toml
	"a"    = "x\ty"
	"a\tb" = "x\ty"

	% cat test.cpp
	#include <iostream>
	#include "toml.hpp"

	int main() {
		auto config = toml::parse_file("test.toml");
		std::cout << config << "\n";
		return 0;
	}

	% c++ -std=c++17 test.cpp

	% ./a.out
	a = 'x	y'
	a	b = 'x	y'

	% ./a.out | hexdump -C
	00000000  61 20 3d 20 27 78 09 79  27 0a 61 09 62 20 3d 20  |a = 'x.y'.a.b = |
	00000010  27 78 09 79 27 0a                                 |'x.y'.|


And that output seems wrong to me? It should have quotes around that key name.

This is with 941341f.

**Comment by marzer** [comment]
Hmmmm, yeah, that output is certainly wrong. Guess I better give it another look O_O

**Comment by arp242** [comment]
The `valid/key/escapes` still fails for the `"\n" = "newline"` test; this gets written back as a literal newline rather than a `\n` escape:

    '
    ' = 'newline'

(it doesn't break anything for me, it just came up on https://arp242.github.io/toml-test-matrix/)

**Comment by marzer** [comment]
Ah crap. Thanks for letting me know.

Also that TOML matrix project is pretty cool!

**Comment by marzer** [comment]
Should be good now @arp242

**Comment by arp242** [comment]
Yup, all pass now :+1:
