### ISSUE TITLE
_Float16 undeclared when compiling on aarch64

### ISSUE THREAD

**Issue by Scrumplex** [marzer/tomlplusplus#178]
## Environment
**toml++ version and/or commit hash:**  cc741c9f5f2a62856a2a2e9e275f61eb0591c09c

**Compiler:**  GNU 12.1.0

**C++ standard mode:**  17

**Target arch:**  aarch64 (arm64)

**Library configuration overrides:**  None

**Relevant compilation flags:**  None?

## Describe the bug

Building toml++ on aarch64 results in the following error:
```
In file included from /run/build/prismlauncher/libraries/tomlplusplus/include/toml++/toml.h:13,
                 from /run/build/prismlauncher/launcher/modplatform/packwiz/Packwiz.cpp:31:
/run/build/prismlauncher/libraries/tomlplusplus/include/toml++/impl/forward_declarations.h:630:29: error: ‘_Float16’ was not declared in this scope; did you mean ‘_Float64’?
  630 |         struct float_traits<TOML_FLOAT16> : float_traits_base<TOML_FLOAT16, __FLT16_MANT_DIG__, __FLT16_DIG__>
      |                             ^~~~~~~~~~~~
In file included from /run/build/prismlauncher/libraries/tomlplusplus/include/toml++/toml.h:39:
/run/build/prismlauncher/libraries/tomlplusplus/include/toml++/impl/forward_declarations.h:630:41: error: template argument 1 is invalid
  630 |         struct float_traits<TOML_FLOAT16> : float_traits_base<TOML_FLOAT16, __FLT16_MANT_DIG__, __FLT16_DIG__>
      |                                         ^
/run/build/prismlauncher/libraries/tomlplusplus/include/toml++/impl/forward_declarations.h:630:63: error: ‘_Float16’ was not declared in this scope; did you mean ‘_Float64’?
  630 |         struct float_traits<TOML_FLOAT16> : float_traits_base<TOML_FLOAT16, __FLT16_MANT_DIG__, __FLT16_DIG__>
      |                                                               ^~~~~~~~~~~~
/run/build/prismlauncher/libraries/tomlplusplus/include/toml++/impl/forward_declarations.h:630:110: error: template argument 1 is invalid
  630 |         struct float_traits<TOML_FLOAT16> : float_traits_base<TOML_FLOAT16, __FLT16_MANT_DIG__, __FLT16_DIG__>
      |                                                                                                              ^
/run/build/prismlauncher/libraries/tomlplusplus/include/toml++/impl/forward_declarations.h:651:29: error: ‘_Float16’ was not declared in this scope; did you mean ‘_Float64’?
  651 |         struct value_traits<TOML_FLOAT16> : float_traits<TOML_FLOAT16>
      |                             ^~~~~~~~~~~~
/run/build/prismlauncher/libraries/tomlplusplus/include/toml++/impl/forward_declarations.h:651:41: error: template argument 1 is invalid
  651 |         struct value_traits<TOML_FLOAT16> : float_traits<TOML_FLOAT16>
      |                                         ^
/run/build/prismlauncher/libraries/tomlplusplus/include/toml++/impl/forward_declarations.h:651:58: error: ‘_Float16’ was not declared in this scope; did you mean ‘_Float64’?
  651 |         struct value_traits<TOML_FLOAT16> : float_traits<TOML_FLOAT16>
      |                                                          ^~~~~~~~~~~~
/run/build/prismlauncher/libraries/tomlplusplus/include/toml++/impl/forward_declarations.h:651:70: error: template argument 1 is invalid
  651 |         struct value_traits<TOML_FLOAT16> : float_traits<TOML_FLOAT16>
      |             
```
Note that this issue does not occur on x86_64 with the same toolchain.

## Steps to reproduce (or a small repro code sample)

Best I can offer is the Flatpak builder here: https://github.com/flathub/org.prismlauncher.PrismLauncher/pull/6

## Additional information
Full build log: https://buildbot.flathub.org/#/builders/42/builds/565/steps/8/logs/stdio

**Comment by Scrumplex** [comment]
I am assuming that c8780a5b8e8d2f8ff1fd747a3a89b7becebfdee9 introduced this, but I don't have an aarch64 machine to test on

**Comment by eddelbuettel** [comment]
Adding to this close / stale issue as we see this with the 3.2.0 code:

- at CRAN the R package RcppTOML around toml++ 3.2.0 fails on arm / aarch64 and i386:
  https://cloud.r-project.org/web/checks/check_results_RcppTOML.html
  
- the Debian compilation of the r-cran-rcpptoml package (based on that CRAN package around toml++ 3.2.0) also fails on arm 
https://buildd.debian.org/status/fetch.php?pkg=r-cran-rcpptoml&arch=arm64&ver=0.2.0%2Bdfsg-1&stamp=1674418861&raw=0

Should we just try to build of the master branch?  Or are you planning a release soon?

**Comment by marzer** [comment]
> Should we just try to build of the master branch? Or are you planning a release soon?

It will be safe to use the current master, but I will be doing a release in the next week or so if you'd prefer to wait - there's a few other small issues on the backlog that I would like to include.

**Comment by eddelbuettel** [comment]
Hm.  Apparently I already took you master branch code when I bootstrapped my repo of rcpptoml around it.  The only difference is in `preprocessor.h` (my copy so from Jan 1):

```sh
edd@rob:~/git/tomlplusplus(master)$ git pull --all
Already up to date.
edd@rob:~/git/tomlplusplus(master)$ rsync -ncav include/toml++/ ../rcpptomlplusplus/inst/include/toml++/
sending incremental file list
impl/
impl/preprocessor.h

sent 2,091 bytes  received 19 bytes  4,220.00 bytes/sec
total size is 636,899  speedup is 301.85 (DRY RUN)
edd@rob:~/git/tomlplusplus(master)$ 
```

Will give that a shot.

**Comment by eddelbuettel** [comment]
Seems to do the trick for arm / aarch64 on macOS:
https://mac.r-project.org/macbuilder/results/1674568326-d3e29b230110ad4b/

**Comment by marzer** [comment]
Yup, I just removed all my attempt at trying to automatically detect `_Float16` support, so now it is entirely opt-in via `TOML_ENABLE_FLOAT16`. Despite my best intentions, compiler bugs kept killing me here.

**Comment by marzer** [comment]
Hmmn? I'm confused. If you enable it everywhere you'll get the same compiler issues you got in 3.2.0.

The thing I removed was the various preprocessor `#ifdefs` that tried to detect `_Float16` support based on the compiler and arch; now it's entirely opt-in such that if you want toml++ to be aware of `_Float16`, you need to explicitly set `TOML_ENABLE_FLOAT16=1`, but doing so on a compiler/arch that does not support it will cause issues.

The only thing it impacts is the ability to directly get/set values as `_Float16`, e.g.:
```cpp
std::optional<_Float16> f16_val = some_node.value<_Float16>();
```
Which is a pretty niche thing, and unlikely to be useful for you given you're wrapping the library anyways. My recommendation would be to explicitly set `TOML_ENABLE_FLOAT16=0`.

**Comment by eddelbuettel** [comment]
I am confused to.  I build RcppTOML in early Jan off your repo then, I should have most fixes but still have the now-removed heuristic of yours to see when to enable float16 support.  That is what I shipped to CRAN, it clearly fails on two platforms:  https://cloud.r-project.org/web/checks/check_results_RcppTOML.html     My fellow Debianer looking after my (usptream) package also has woes.  

I then confused myself once more by using the machine accessible at https://mac.r-project.org/macbuilder/submit.html but the CRAN arm64 aka aarch64 build already passed, it was the _plain old_ macOS that failed per the table in
   https://cloud.r-project.org/web/checks/check_results_RcppTOML.html
with log at
   https://www.r-project.org/nosvn/R.check/r-release-macos-x86_64/RcppTOML-00install.html
and that looks like a ... compiler issue / the choice of
   `clang++ -mmacosx-version-min=10.13 -std=gnu++17` 
creating woes.  So different issue.

Back to float16.  So when/where should I enable?  Only on i386?  Why does arm64 fail at Debian in 
https://buildd.debian.org/status/fetch.php?pkg=r-cran-rcpptoml&arch=arm64&ver=0.2.0%2Bdfsg-1&stamp=1674418861&raw=0  (and scroll to bottom) when it is 64 bit?

**Comment by eddelbuettel** [comment]
> My recommendation would be to explicitly set TOML_ENABLE_FLOAT16=0.

I am extra dense today.  Thank you. 

I thought our woes were from wanting to _enable_ rather than explicitly _disable_ where it may fail.
