### ISSUE TITLE
Optional `get`

### ISSUE THREAD

**Issue by A-F-V** [marzer/tomlplusplus#180]
**Is your feature request related to a problem? Please describe.**

I'd like a way to get nodes and sub tables in an optional without using `get` and checking for nullptr.

**Describe the solution you'd like**

A function possibly named `get_optional` that is similiar to `value` except which operates over tables and arrays and places the subnode inside an optional. For example, if we had a toml:
```
[outer.inner]
x=5
```
Then, `toml.get_optional<toml::table>("inner")` should return `std::optional<toml::table>` with the inner table as it's value.

**Comment by marzer** [comment]
This is what node views are for - chain them together to reduce verbosity, e.g. `toml["outer"]["inner"]` is safe even if `outer` didn't exist.

**Comment by marzer** [comment]
https://marzer.github.io/tomlplusplus/classtoml_1_1node__view.html
