### ISSUE TITLE
Conversion from double to string is locale-dependent if TOML_FLOATING_POINT_CHARCONV is 0

### ISSUE THREAD

**Issue by traversaro** [marzer/tomlplusplus#19]
## Environment
**Compiler:**  
Any compiler that does not support `to_chars` for `double` , i.e. for  which `TOML_FLOATING_POINT_CHARCONV` is 0.

**C++ standard mode (e.g. 17, 20, 'latest'):**  
17

**Target arch (e.g. x64):**  
Not relevant.

**Exceptions enabled:**  
Not relevant.

**Relevant `toml++` configuration customizations:**  
Not relevant.

**Relevant compilation flags:**  
Not relevant.

## Describe the bug
When `TOML_FLOATING_POINT_CHARCONV` `std::ostringstream` is used  to convert a double to a string in https://github.com/marzer/tomlplusplus/blob/v1.1.0/include/toml++/toml_parser_impl.h#L153 .  However, the [`imbue`](https://en.cppreference.com/w/cpp/io/basic_ios/imbue) method is not called, so the default locale, that is the global C++ locale set in https://en.cppreference.com/w/cpp/locale/locale/global . If it is intended to have the same behavior independently from the value `TOML_FLOATING_POINT_CHARCONV`, I guess it is necessary to call `ss.imbue(std::locale::classic());` after the `ss` object is declared. I did not checked other code paths if `TOML_FLOATING_POINT_CHARCONV` is set to 0, but it is possible that they are affected as well. 

## Additional information
Related issues: 
* https://github.com/robotology/idyntree/issues/288
* https://github.com/ros/urdfdom_headers/pull/42

cc @S-Dafarra @GiulioRomualdi

**Comment by marzer** [comment]
Oh, thanks for bringing this to my attention @traversaro!

**Comment by marzer** [comment]
@traversaro I've implemented a fix locally but in testing some additional locale machinery I uncovered a few other related issues, which I'll fix tomorrow before pushing anything.

**Comment by marzer** [comment]
@traversaro The fix for this is live now. Solving this forced me to learn about locales on unix and to add different locales to my CI pipeline, so any locale-based regressions should be caught in future.

**Comment by traversaro** [comment]
Thanks a lot. I reported these kind of locale-related bugs to several open source projects over the years, but I never saw something as complete as the testing infrastructure that you set up!
