### ISSUE TITLE
Key access function that throws on key not found

### ISSUE THREAD

**Issue by OlafvdSpek** [marzer/tomlplusplus#193]
**Is your feature request related to a problem? Please describe.**

```
    // different ways of directly querying data
    std::optional<std::string_view> str1 = tbl["str"].value<std::string_view>();
    std::optional<std::string>      str2 = tbl["str"].value<std::string>();
    std::string_view                str3 = tbl["str"].value_or(""sv);
    std::string&                    str4 = tbl["str"].ref<std::string>(); // ~~dangerous~~

    std::cout << *str1 << "\n"; // 1
    std::cout << *str2 << "\n"; // 2
    std::cout << str3 << "\n";
    std::cout << str4 << "\n";
```
1. and 2. have undefined behavior if it's a nullopt, `.value()` might be safer.
`.value()` would throw `bad optional access`, which doesn't tell a lot about the cause or location of the issue.

https://marzer.github.io/tomlplusplus/#mainpage-example-manipulations

**Describe the solution you'd like**
A key access function that'd throw on key not found with an error message containing the name of the key would be helpful.
A value access function that'd throw on wrong data type might be helpful too.

**Comment by marzer** [comment]
> and 2. have undefined behavior if it's a nullopt

Well yeah, that just means you're violating the contract of std::optional, which is not a problem my library needs to address - that is solved simply by reading cppreference.com. std::optional is a vocabulary type and it's use should be encouraged, not avoided.

**Comment by marzer** [comment]
Oh, also: toml::table and toml::array both have an `at()` method that will throw that exception in the same way a std::vector does, so you can actually already get this behaviour if you first get the source node as a table/array:

- [toml::array::at()](https://marzer.github.io/tomlplusplus/classtoml_1_1array.html#a3ab7998d733b37f51c687f7d892c205f)
- [toml::table::at()](https://marzer.github.io/tomlplusplus/classtoml_1_1table.html#a09e2c0437700b2a4e5c031e046a07b90)
```

These are intended for more advanced use, whereas `value()` 'just works' regardless of what the concrete node actually is, so you can pick your poison.

**Comment by OlafvdSpek** [comment]
> is an assumption made for the sake of the example.

It's not like using `.value()` makes the example (significantly) more complex.

> so changing value() to rely on exceptions is a non-starter for people relying on that)

I'm not requesting existing semantics to be changed.

**Comment by marzer** [comment]
> I'm not requesting existing semantics to be changed.

Yeah, I initially mis-read your request. Either way, for slightly more advanced usage this is already implemented via `at()`.

In any case my points about std::optional being a vocabulary type are valid; I could implement something like `value_or_throw()`, _or_ people could just use `std::optional::value()` for checked-access semantics, if that's what they need. The standard library already has you covered here.

**Comment by marzer** [comment]
If you genuinely believe the example should be changed to emphasize the specifics of using `std::optional` here then I'll happily accept a PR, but otherwise I don't think I'll bother.

**Comment by OlafvdSpek** [comment]
> In any case my points about `std::optional` being a vocabulary type are valid; I could implement something like `value_or_throw()`, _or_ people could just use `std::optional::value()` for checked-access semantics, if that's what they need. The standard library already has you covered here for the general case, and for more advanced usage requiring better error mesages this is already implemented via `at()`.

`at()` indeed perfectly covers "A key access function that'd throw on key not found with an error message containing the name of the key would be helpful."

What about "A value access function that'd throw on wrong data type might be helpful too." though?
`bad optional access` doesn't provide enough useful info to the user.

**Comment by marzer** [comment]
I'll think about it. Having both complicates the implementation quite a bit so I'd rather not.

In the interim if you want a message that says something like `value error: tried to get type 'bool' as type 'string'` all the tools to do this are in the library now and could be implemented easily in a helper function in your own code.

**Comment by OlafvdSpek** [comment]
> all the tools to do this are in the library now and could be implemented easily in a helper function in your own code.

True. But if multiple library users have to write the same helper function, it'd make sense to just include it in the library.

**Comment by marzer** [comment]
> it'd make sense to just include it in the library.[...]

What 'makes sense' is up to me. I said I'd think about it, but to reiterate: this implies a very annoying complication of the implementation, so currently I am at a firm "maybe", especially since you're the first user in a number of years to ask for this. Let's leave it at that.
