### ISSUE TITLE
std::aligned_storage and std::aligned_storage_t are deprecated in C++23

### ISSUE THREAD

**Issue by OlafvdSpek** [marzer/tomlplusplus#194]
On VS 2022 Preview 17.6

`
toml++\impl\table.h(40,16): warning C4996: 'std::aligned_storage_t': warning STL4034: std::aligned_storage and std::aligned_storage_t are deprecated in C++23. Prefer alignas(T) std::byte t_buff[sizeof(T)]. You can define _SILENCE_CXX23_ALIGNED_STORAGE_DEPRECATION_WARNING or _SILENCE_ALL_CXX23_DEPRECATION_WARNINGS to suppress this warning.
`

**Comment by marzer** [comment]
This has already been addressed in 59ad6e6, which was included in the v3.2.0 release. You need to use a more recent version of the library :)

**Comment by marzer** [comment]
Oh, is it? Guess I should probably address that! Thanks for letting me know.
