### ISSUE TITLE
CMake FetchContent documentation should specify GIT_SUBMODULES_RECURSE

### ISSUE THREAD

**Issue by andrewkcorcoran** [marzer/tomlplusplus#195]
The documentation for using the library with submodules specifies that you shouldn't recurse submodules for normal consumption. The documentation for using the library with CMake FetchContent omits this detail and doesn't mention that from CMake 3.17 you can disable FetchContent  submodule recursion using the GIT_SUBMODULES_RECURSE option (which will get forwarded from FetchContent to https://cmake.org/cmake/help/latest/module/ExternalProject.html#id1)

**Comment by marzer** [comment]
Oh, it's actually much simpler than that; the documentation note about submissions l submodules is wrong and should be deleted. I moved away from using git submodules wow a while ago and I guess I forgot to delete that note at the time.
