### ISSUE TITLE
aarch64-linux-gnu-g++ version 7.5.0 crash with segmentation fault

### ISSUE THREAD

**Issue by sagi-ottopia** [marzer/tomlplusplus#197]
## Environment
**toml++ version and/or commit hash: 7eb2ffcc09f8e9890dc0b77ff8ab00fc53b1f2b8 v3.3.0**  

**Compiler: aarch64-linux-gnu-g++ (Linaro GCC 7.5-2019.12) 7.5.0**  

**C++ standard mode: c++17**  

**Target arch: aarch64**  

**Library configuration overrides:**  

**Relevant compilation flags:**  

## Describe the bug

While trying to build the examples with the following commands:
compiler crashed with segmentation fault

## Steps to reproduce (or a small repro code sample)

```
$ cmake -B build.gcc7 -DBUILD_EXAMPLES=1 -DCMAKE_CXX_COMPILER=/opt/toolchains/gcc-linaro-7.5.0-2019.12-x86_64_aarch64-linux-gnu/bin/aarch64-linux-gnu-g++
$ cmake --build build.gcc7 --verbose
```

## Additional information

![image](https://user-images.githubusercontent.com/95352874/226951808-8debb320-89bf-47f3-a1b2-a0a7279cc56e.png)

**Comment by marzer** [comment]
Ah yup, I've had trouble with other older versions of GCC with over-alignment in the past, looks like more of the same. Should be easy to address, thanks for the report :)

**Comment by sagi-ottopia** [comment]
Thank you for the quick response, currently I can't upgrade the compiler version that I use on that platform so a fix will be very helpful

**Comment by sagi-ottopia** [comment]
Yes, `simple_parser` compiles OK.
but I started to compile the examples code because when I'm compiling my code which uses the library this particular compiler crashed as well.

**Comment by marzer** [comment]
Ah, OK, I see. Well I'll try to come up with a workaround but it might ultimately be the case that GCC 7 is a bit too broken - the lowest I'm able to easily test with these days is GCC 8.

**Comment by damirbarr** [comment]
Hi @marzer 
Is there anything new with this issue?

**Comment by marzer** [comment]
@damirbarr are you also experiencing the same issue? If so, which specific version of GCC and target environment, the same one as @sagi-ottopia?

**Comment by marzer** [comment]
> I applied the following patch and was able to work around this issue.

Hmmn, interesting. A worrying factor - a `bool` (or `bool`-convertible) return result of `false` from the `for_each()` callback is supposed to stop the iteration; your workaround deletes the branches responsible for handling that and always returns `true`, which effectively changes the API. Are you able to do some less destructive alterations, to find which specific construct in `do_for_each` triggers the ICE?

If I can't modify `for_each` to support the `bool` propagation and have it still work on GCC 7 I will have to deprecate support for GCC 7, unfortunately.

> All my unit tests pass and I'm able to compile everything.

Looks like I am missing tests to ensure `for_each()` iteration does what it's supposed to do when you return `false` :P

**Comment by marzer** [comment]
@damirbarr In 2414d904a837aa2d0b795f086081df2d53b57d98 I have added some additional tests to check for the above

**Comment by sagi-ottopia** [comment]
> Ah, OK, I see. Well I'll try to come up with a workaround but it might ultimately be the case that GCC 7 is a bit too broken - the lowest I'm able to easily test with these days is GCC 8.

1. I can assist with checking on a relevant compiler and a machine. I have a cloud machine installed with Ubuntu 18.04 ARM64 
2. You can download the compiler from https://releases.linaro.org/components/toolchain/binaries/latest-7/aarch64-linux-gnu/  

Sagi.

**Comment by marzer** [comment]
Alright folks, sorry it took me so long to get back to this. I wasn't able to come up a workaround that preserved the same API (returning `false` to early exit the loop), so instead I've added an error message and some `#define` escape hatches.

- By default, using a `for_each()` on GCC 7 will trigger a static assert
- `#define TOML_RETURN_BOOL_FROM_FOR_EACH_BROKEN 0` indicates "no actually my compiler works fine, I want the normal API" (YMMV)
- `#define TOML_RETURN_BOOL_FROM_FOR_EACH_BROKEN_ACKNOWLEDGED` indicates "yep, that's fine, I don't need to be able to early-exit from `for_each()`" (essentially this enables @damirbarr's patch)
