### ISSUE TITLE
Detection of (and testing with) other compilers

### ISSUE THREAD

**Issue by marzer** [marzer/tomlplusplus#2]
ICC, for example. I don't have ready access to it so it makes testing for it a bit challenging.

I could use something like [Hedley](https://nemequ.github.io/hedley/) but I'd like to keep toml++ self-contained. Cherry-picking from hedley is on option too, of course (with appropriate attribution obviously).

**Comment by jwillikers** [comment]
Support for MSVC would be great! Unfortunately, I have a lot of CMake experience and none with Meson or Hedley.

**Comment by marzer** [comment]
@jwillikers It already has full support for MSVC (in VS 2019, at least), since that's my daily-driver. The solution in the `vs/` subfolder has a whole smattering of test projects specficially for MSVC. I haven't tested older versions of it, but then C++17 support in VS2017 was sketchy at best so I figured it would probably be a waste of time (in that most people that really wanted to use C++17 and 20 features would likely have made the switch).

I guess this issue really should be made more specific, something akin to "Tests on ICC and Apple-flavoured Clang"...

**Comment by marzer** [comment]
I suppose I should mention prominently in the README the platforms I already test on/for, too.

**Comment by jwillikers** [comment]
@marzer Aww yes... the `vs` folder should have been a clue 😅 I'm definitely talking about VS 2019. Thanks!

**Comment by marzer** [comment]
Did some testing with ICC recently and was able to detect the meaningful parts easily enough. I'll consider this 'done' for the time being, and re-open it if someone comes at me with a more obscure compiler.
