### ISSUE TITLE
File generated can't be parsed.

### ISSUE THREAD

**Issue by Raildex** [marzer/tomlplusplus#206]
I use MSVC with c++latest with toml++ v3.3.0
I use an ifstream to write a file.
The writing seems to work correctly.

but reading the same file results in a parser error:

> Error while parsing boolean: encountered end-of-file

[settings.toml.txt](https://github.com/marzer/tomlplusplus/files/12715782/settings.toml.txt)

**Comment by marzer** [comment]
Can you show me your code? I have a unit test that covers this scenario.

Also please don't delete bug report templates and roll your own. The template even asks you not to do that.

Re-report this with the template filled out properly and a code sample, please.
