### ISSUE TITLE
OSS-Fuzz Integration

### ISSUE THREAD

**Issue by capuanob** [marzer/tomlplusplus#208]
**Is your feature request related to a problem? Please describe.**
I have submitted this project to OSS-Fuzz and received word that they would like to accept this project, with the maintainer's approval. I wanted to reach out to see if this is something that you would support me integrating into your CI/CD pipeline. 

**Describe the solution you'd like**
If approved, I will integrate tomlplusplus into OSS-Fuzz for continuous fuzz-testing of the project. I will then integrate ClusterFuzz into this project's build pipeline to detect any vulnerabilities that could be introduced by PR changes. This would be free of charge to the project maintainer and I would undertake the work. 

**Additional context**
If approved, what email would you like me to include to be CC'd in any critical security bug reports that are encountered during continuous fuzzing

**Comment by marzer** [comment]
Hi there, sure, that'd be great! `mark.gillard@outlook.com.au` is fine :)
