### ISSUE TITLE
Support for compiling without `<charconv>`

### ISSUE THREAD

**Issue by marzer** [marzer/tomlplusplus#21]
Because some older C++17 compilers don't have it in their stdlib implementation.

**Comment by marzer** [comment]
CC @traversaro

**Comment by GiulioRomualdi** [comment]
Thanks @marzer! That would be amazing. It will enable the compilation with `gcc 7.4.0` on `Ubuntu 18.04 `

Related issue: https://github.com/dic-iit/bipedal-locomotion-controllers/issues/26#issuecomment-609456247

**Comment by marzer** [comment]
There you go @GiulioRomualdi, just pushed the implementation for this! I've added it to my internal tests for GCC7 here on my development machine. I haven't made it part of the CI pipeline yet because that means making a new docker image, but I'll get around to it at some point.

**Comment by GiulioRomualdi** [comment]
Thanks @marzer! Everything is working fine
