### ISSUE TITLE
How to convert toml::date_time to std::chrono::time_point?

### ISSUE THREAD

**Issue by Gwill** [marzer/tomlplusplus#210]
How to convert toml::date_time to std::chrono::time_point?

**Comment by marzer** [comment]
There's no built-in way to do this; you'd need to do a bit of math. I'm not very familiar with `std::chrono` so I can't think how to do this currently, but I'll have a look into it.

**Comment by marzer** [comment]
Looks like the snippets here are what you want; https://stackoverflow.com/questions/52238978/creating-a-stdchronotime-point-from-a-calendar-date-known-at-compile-time
