### ISSUE TITLE
What is the proper way to parse top level arrays? Seems not working

### ISSUE THREAD

**Issue by degloff** [marzer/tomlplusplus#223]
How can this simple toml file be parsed?

```
[[elems]]
a = 1
b = 2

[[elems]]
a = 10
b = 20
```

It should be an array so once parsing the table, `tbl["elems"]` should be an array or array of tables but it is not. 

What is wrong here? I use VS 2022. 

Thanks for a hint how to use it properly.

**Comment by marzer** [comment]
Please use the bug report templates.

**Comment by degloff** [comment]
Hm seems to work if I use the cast like this: `*tbl.get_as<toml::array>("elems")`. Interesting.

**Comment by degloff** [comment]
Let me dig a bit deeper. And thanks for quick reply.

**Comment by marzer** [comment]
I suggest you see the [Working with TOML data](https://marzer.github.io/tomlplusplus/#mainpage-example-manipulations) section of the main page for usage examples.

**Comment by varugasu** [comment]
@marzer, just to be clear and give visibility for anyone visiting this thread. I have a TOML file like this:

```toml
[Camera]
position = [0.0, 8.0, -10.0]
```
So we are supposed to iterate/access each item in the `position` array and then cast to the desired value. Like this:

```cpp
Vector3 GetCameraPosition(toml::table &scene) {
  auto cameraPosition = scene["Camera"]["position"].as_array();
  Vector3 position;
  position.x = cameraPosition->at(0).value<float>().value_or(0.0f);
  position.y = cameraPosition->at(1).value<float>().value_or(0.0f);
  position.z = cameraPosition->at(2).value<float>().value_or(0.0f);

  return position;
}
```
