### ISSUE TITLE
Ask for the "PrivacyInfo.xcprivacy" required by Apple 

### ISSUE THREAD

**Issue by baihao** [marzer/tomlplusplus#228]
Ask for the plan to include the `PrivacyInfo.xcprivacy` manifest as required by Apple

**Is your feature request related to a problem? Please describe.**
Apple requires the app or third-party SDK has a privacy manifest file to record the following information:

- The types of data collected by your app or third-party SDK. You need to provide this information for your app or third-party SDK on all platforms.
- The required reasons APIs your app or third-party SDK uses. You need to provide this information for your app or third-party SDK on iOS, iPadOS, tvOS, visionOS, and watchOS.

Please refer to https://developer.apple.com/documentation/bundleresources/privacy_manifest_files?language=objc for more detailed information

**Describe the solution you'd like**
Provide the manifest file `PrivacyInfo.xcprivacy` according to Apple's requirement.

**Additional context**
None

**Comment by marzer** [comment]
...this library is a header-only library, and should not need any of that 😅

If you would like to contribute whatever this is via PR, then be my guest, but I'm not going to add this myself.
