### ISSUE TITLE
meson.build installed in /usr/local/include/ ??

### ISSUE THREAD

**Issue by JWCS** [marzer/tomlplusplus#236]
I'm noticing a `/usr/local/include/meson.build` being added by the cmake install command.
Is this not supposed to be there?

## Environment
I'm installing this in a docker; here's my installation commands.
``` docker
WORKDIR /dep/tomlpp
RUN git clone --depth 1 -b "v3.4.0" \
    https://github.com/marzer/tomlplusplus.git .
RUN mkdir build && cd build && \
    cmake .. && cmake --build . && cmake --build . --target install
```

**Compiler:**  
GCC 9.4.0
NINJA 1.10.0
CMake 3.30 or so, latest stable
All were installed in ubuntu 22 server docker image:
`apt install cmake ninja-build make g++`, with minor exception for newer cmake version.

**C++ standard mode:**  
The default for GCC 9.4.0, for v3.4.0. I'm not specifying anything.

**Target arch:**  
ARM64

**Library configuration overrides:** 
No changes from the github.

**Relevant compilation flags:**  
No changes from the github.

## Describe the bug
I might be confused, but I don't think any... generic files like meson.build should be in /usr/local/include/.

## Steps to reproduce (or a small repro code sample)
See above, the docker snibbit.

**Comment by marzer** [comment]
Hmmn, yeah, that's not correct 😅 I haven't actually taken much of a look at the CMake integration as it was added by a contributor and I didn't know CMake at the time. That's changed now, though, I've been (unfortunately) forced to learn it quite well recently. Will take a look.

**Comment by marzer** [comment]
Fixed in `main`, thanks for the report :)
