### ISSUE TITLE
How to retrieve the C++ underlying value (string, double, integer, bool...)?

### ISSUE THREAD

**Issue by SuperFola** [marzer/tomlplusplus#25]
Hey there,
I came accross your lib, and the documentation doesn't cover how to retrieve the stored data.
I'm reading a configuration file, and need to retrieve a string here, a flot there, but `std::string spriteSheet = table["data"]["spriteSheet"].get()` is saying that it can't convert a node* to a string, with

```toml
[data]
spriteSheet="hello.gif"
```

Thanks in advance

**Comment by marzer** [comment]
The object you get back from table's operator[] is a node view, and has a bunch of conversion/retrieval member functions. See [here](https://marzer.github.io/tomlplusplus/classtoml_1_1node__view.html) for node view API documentation.

I'm on the road atm so can't reply in more detail, but give that a look and let me know how you go.

**Comment by SuperFola** [comment]
So it's a combination of as_type() and get(), like `table["data"]["spriteSheet"].as_string()->get()` is I understand correctly.

Thanks, I missed this page

**Comment by marzer** [comment]
@SuperFola Yup, pretty much. If you're not interested in the actual node and just want to get right to the value you can also use one of:
- [`value()`](https://marzer.github.io/tomlplusplus/classtoml_1_1node.html#ab144c1ae90338b6b03f6af0574c87993) a pointer to the raw value, or nullptr if it didn't exist or was a different type
- [`value_or()`](https://marzer.github.io/tomlplusplus/classtoml_1_1node.html#a423ddccc36345545615e20290c9a8a65): The underlying value, or some default if it didn't exist or was a different type
- [`ref()`](https://marzer.github.io/tomlplusplus/classtoml_1_1node.html#a669d39909c44e25dccf8816a038ce4ef): An lvalue reference to the actual value; assumes the value exists and already is of the correct type

All three are available from nodes and node views.
