### ISSUE TITLE
iterators returned during iteration ought to also implement first and second

### ISSUE THREAD

**Issue by ned14** [marzer/tomlplusplus#30]
Right now, iterators of tables return a value item with `key` and `value`.

It would suit genericity better if they also contained `first` and `second`, to match the STL. This may appear to double the size of the proxy pair, but if you place them last in the structure, and consuming code doesn't use them, you'll find GCC and clang elide the storage for them under optimisation. They therefore become "free".

**Comment by marzer** [comment]
Hmmn. Interesting. If I understand correctly, you're saying that these two will get optimized down to the same thing if `first` and/or `second` aren't ever referenced?

```cpp
struct ref_pair1
{
	const string& key;
	int& value;
	const string& first;
	int& second;
};

struct ref_pair2
{
	const string& key;
	int& value;
};
```

**Comment by ned14** [comment]
So long as `ref_pair1` never could escape, then yes the compiler will eliminate the extra storage entirely. I use this technique in `path_view::c_str` which is being standardised, it has a 1Kb array at its end it may use for zero terminating the path view before giving it to a syscall. If the compiler can statically prove that that the path view's input is zero terminated (e.g. it comes from a string literal), and thus the buffer never gets used, it completely eliminates it from codgen. Which is pretty cool.

**Comment by marzer** [comment]
Damn, that's kinda amazing. TIL.

**Comment by marzer** [comment]
Decided to fully lean into consistency with the STL and just rename the elements to `first` and `second` instead. (Obviously I'd prefer the more semantically-meaningful names, but principle of least surprise, etc.). I would have liked to use your idea but it breaks structured bindings (i.e. `auto [k, v]` would have to become `auto [k, v, kk, vv]` or similar).
