### ISSUE TITLE
toml::array is missing resize() operation

### ISSUE THREAD

**Issue by ned14** [marzer/tomlplusplus#33]

**Comment by marzer** [comment]
@ned14 This is by design; if a call to resize() makes it larger, what should the new node elements be initialized as? Integers with value `0`? Empty strings? There isn't really a logical choice here; since more than one is reasonable, that implicitly means that none of them are.

**Comment by marzer** [comment]
I guess I could provide a `resize()` operation with a default value, e.g. `resize(size_t, string_view)` creating strings with the given value if the array needs to grow.

**Comment by ned14** [comment]
I specifically tried to use it to truncate an overly long array to smaller, and when it wasn't there, that was surprising. I guess `.truncate()` would do? Otherwise, yes resize with a default value also works, or resize failing if you try to use it for expansion.

**Comment by marzer** [comment]
Ooh, yes, `truncate()` is nice and clear, I think. I'll go with that over providing a `resize()` that's only good for shrinking. I'll also add `resize(size_t, <default value>)` while I'm at it.

**Comment by marzer** [comment]
Added in 289c95c:
- `resize(size_t, <default value>)`
- `truncate(size_t)`
- `max_size()`, `capacity()`, `shrink_to_fit()` for additional consistency with std::vector
