### ISSUE TITLE
Empty file is valid toml file

### ISSUE THREAD

**Issue by bobfang1992** [marzer/tomlplusplus#35]
Hi,

Just want to mention that from what I can see, most toml parser implementation will be happy to take an empty file as input instead of raise but tomlplusplus seems to be doing the opposite. I would think this is not a bug but just different choices made by the developer. In my humble opinion, I think returning an empty table, in this case, is not outrageous compared to raising a run time error as tomlplusplus does now.

Happy to hear your thought.

Bob

**Comment by bobfang1992** [comment]
Some example:
```
In [1]: import tomlkit                                                                                                                                                                                                                                                                             

In [2]: import tomlkit                                                                                                                                                                                                                                                                             

In [3]: tomlkit.loads("")                                                                                                                                                                                                                                                                          
Out[3]: {}

```

**Comment by bobfang1992** [comment]
The problem here is that tomlplusplus itself is happy to take an empty string when I use ``parse``, but when using ``parse_file``, the code checks if the result we get is zero-length then tpp will throw.

**Comment by marzer** [comment]
Oh, yeah you're right; a blank file is still perfectly valid TOML. Thanks for pointing this out!
