### ISSUE TITLE
A python wrapper!

### ISSUE THREAD

**Issue by bobfang1992** [marzer/tomlplusplus#36]
Hi,

Maybe I am getting excited too early but I have made a python wrapper for this awesome library, here is my repo: https://github.com/bobfang1992/pytomlpp

I have done the deserializing part but has yet to do the serializing part. But its taking shape quite fast.

This is just more like to inform you about this. If you have any comments I am happy to know.

Best,
Bob

**Comment by marzer** [comment]
Oh, hey, that's awesome! Let me know when it's finished and I'll add some links to it to this repository's README etc.

**Comment by marzer** [comment]
@bobfang1992 I took a look at your repo and noticed that in your README you've listed benchmarks as a reason to switch to your wrapper library over one of the alternatives. This led me to doing some profiling of my own and finding a few ways to speed up `toml++` itself, particularly when using `toml::parse_file()`. It might be worth re-running your benchmark using the current master version of `toml++` to see if you get better results :)

**Comment by bobfang1992** [comment]
@marzer hey thanks I will look into this. Sorry was busy with some my personal stuff and the development stopped for a bit but I will resume this week and make some progress.

Best,
Bob

**Comment by bobfang1992** [comment]
Cool, this is done now. I have updated the repo and now it supports `load`, loads`, `dump`, `dumps` and it's using 1.3.2. I have done the benchmarking again but I did not see much difference for parsing performance BTW.

Anyway, I think this is ready to ship as :).

**Comment by marzer** [comment]
Ah, that's interesting. I guess the overhead of python far overshadows the gains in the native code (I saw 3-4x speedups).

**Comment by bobfang1992** [comment]
Hey, shall we add a line to mention the python wrapper in the official website and then we can close this issue? Eager to hear you thought! Thanks!

**Comment by marzer** [comment]
Aye, sure. I need to do a bit more work on the main page to bring some missing info from the README, so I'll bundle it in with those changes.

**Comment by marzer** [comment]
Here you go @bobfang1992 : https://marzer.github.io/tomlplusplus/?#mainpage-adding-lib-python

**Comment by bobfang1992** [comment]
Thanks this is great!
