### ISSUE TITLE
toml table to string/file?

### ISSUE THREAD

**Issue by seppy87** [marzer/tomlplusplus#37]
**Is your feature request related to a problem? Please describe.**
I have a Problem. How can I convert a toml::table to string, so I can save it as file?

**Describe the solution you'd like**
a function dump() which returns the string to save it to a file or a direct function table.saveFile

**Describe alternatives you've considered**
Need to code a work around with for loops

**Comment by marzer** [comment]
This is already supported natively via overloaded ostream operators. In your case you can just write it directly to an instance of `std::ofstream`. See the [Serializing as TOML and JSON](https://marzer.github.io/tomlplusplus/#mainpage-example-serialization) example in the API docs.
