### ISSUE TITLE
"key = -1" parses as "key = 1"

### ISSUE THREAD

**Issue by ned14** [marzer/tomlplusplus#39]
If you examine https://github.com/marzer/tomlplusplus/blob/master/include/toml%2B%2B/toml_parser.hpp#L1950:

```c++
						// single-digit signed integers
						if (char_count == 2_sz && has_any(has_digits))
						{
							val = std::make_unique<value<int64_t>>(
								static_cast<int64_t>(chars[1] - U'0')
								* (chars[1] == U'-' ? -1LL : 1LL)
							);
							advance(); //skip the sign
							advance(); //skip the digit
							break;
						}
```
... the check for the minus sign is wrong, it should be checking `chars[0]`, not `chars[1]`. Hence all negative numbers in TOML become positive!

**Comment by marzer** [comment]
Oh crap. Nice find.

Worth noting that not all number values will become positive due to this bug, only single-digit integers. Doesn't help you much, though! I'll push a fix tomorrow. Thanks @ned14

**Comment by marzer** [comment]
Fixed in master. Thanks again @ned14! That one was embarrassing. My tests covered negative integers but I'd forgotten to cover the special-case path for single-digit ones :(
