### ISSUE TITLE
More documentation!

### ISSUE THREAD

**Issue by marzer** [marzer/tomlplusplus#4]
Writing documentation is kinda hard. Coming up with nice examples in said documentation is even harder. This will be an ongoing issue for me, and I welcome any contributions!

**Comment by jwillikers** [comment]
Hi @marzer, thanks for all of your work on this library. The API looks beautifully simple. When choosing whether to use a library like this, it is very helpful for me to see examples of the error messages from the error-handling functions. In your documentation, I saw the error-handling examples but they didn't show the full output for a sample case. That would be helpful for me to see. Thanks!

**Comment by marzer** [comment]
@jwillikers Thanks, glad you like it!

That's a good idea, I should add a few failure cases to the example code. In the mean-time you can get a good idea of how they're formatted and their level of detail by skimming through `toml_parser.h` and picking out the occurences of `abort_with_error()`.

**Comment by jwillikers** [comment]
@marzer Thanks, I appreciate it!

**Comment by marzer** [comment]
Checklist of documentation stuff for me to do when I get the chance:
- [ ] Add examples of error messages to the index page and `parse_result`'s brief
- [ ] Boolean literals in code blocks are bold white, but really should be blue like keywords (see `operator<<(ostream, node_type)`)
- [ ] The `Contributing` link on the front page of the HTML docs refers to README.md but should refer to CONTRIBUTING.md
- [ ] Add a prominent listing of the currently tested platforms and compilers to the README.md and HTML docs

**Comment by marzer** [comment]
@jwillikers In addition to a few minor code bugfixes I've just pushed a bunch of documentation improvements that might be relevant to your interests.
