### ISSUE TITLE
C++20 MSVC Syntax Error [CMake]

### ISSUE THREAD

**Issue by okureta** [marzer/tomlplusplus#41]
## Environment
**Compiler:**  
MSVC

**C++ standard mode (e.g. 17, 20, 'latest'):**  
C++20

**Target arch (e.g. x64):**  
x64

**Exceptions enabled:**  
I am using the default (/EHsc) Exceptions

**Relevant `toml++` configuration customizations:**  
No overrides are used

**Relevant compilation flags:**  
None

## Describe the bug
Syntax/Unknown-Type/Traits errors.
```
toml.hpp(8103): error C2589: '(': illegal token on right side of '::'
toml.hpp(8612): note: see reference to function template instantiation 'int64_t toml::impl::abi_impl_noex::parser::parse_integer<16>(void) noexcept' being compiled
toml.hpp(8103): error C2062: type 'unknown-type' unexpected
toml.hpp(8103): error C2144: syntax error: 'unknown-type' should be preceded by '('
toml.hpp(8103): error C2059: syntax error: ')'
toml.hpp(8104): error C2143: syntax error: missing ';' before '{'
toml.hpp(8104): error C2059: syntax error: ','
toml.hpp(8104): error C2059: syntax error: ')'
toml.hpp(8104): error C2059: syntax error: 'return'
toml.hpp(8104): error C2059: syntax error: '}'
toml.hpp(8108): error C2059: syntax error: 'if'
toml.hpp(8108): error C2653: 'traits': is not a class or namespace name
toml.hpp(8110): error C2059: syntax error: 'else'
toml.hpp(8112): error C2059: syntax error: '}'
toml.hpp(8112): error C2143: syntax error: missing ';' before '}'
```

## Steps to reproduce (or a small repro code sample)
Include it in any source file.

## Additional information

Screenshots of the compiler error:
![image](https://user-images.githubusercontent.com/29059450/85202804-e2859a80-b300-11ea-9a0d-d276daf556cb.png)

**Comment by okureta** [comment]
Also, no modifications were made to the header. I tried both the "Single Header Flavor" and "Regular Flavour". They both threw this error.

**Comment by okureta** [comment]
^ However the Regular Flavour had errors on the array and parser files. If you would like the error messages let me know.

**Comment by marzer** [comment]
Hmm, weird. MSVC is the environment I use to develop TOML++ so it's weird that I didn't see this. I'll do some investigating.

Can you tell me the value of _MSC_FULL_VER?

**Comment by okureta** [comment]
> Hmm, weird. MSVC is the environment I use to develop `toml++` so it's weird that I didn't see this. I'll do some investigating. Two things I need from you:
> 
> 1. Tell me the value of _MSC_FULL_VER from your compiler (or build with /Bv and tell me the version it spams you with at compile-time)
> 2. Open the `toml++` visual studio solution (`tomlplusplus/vs/toml++.sln`) and try building any of the example projects, and tell me what happens.

Thank you for the quick reply,

The value: _MSC_FULL_VER: 192628806

And for the Visual Studio solution, even though my CLion project is using the same compiler, compiled successfully!
![image](https://user-images.githubusercontent.com/29059450/85210382-3b702580-b337-11ea-8452-722a371489e9.png)

I find this really strange.

**Comment by marzer** [comment]
Hmm, yeah. It seems like a CMake-related issue. Are you able to see the full command line that gets sent to MSVC anywhere? If so, post that. My suspicion is that MSVC isn't being invoked with the right C++ standard level.

**Comment by okureta** [comment]
```Command line: "cmd.exe" /c ""c:\program files (x86)\microsoft visual studio\2019\community\common7\ide\commonextensions\microsoft\cmake\CMake\bin\cmake.exe"  -G "Ninja" -DCMAKE_INSTALL_PREFIX:PATH="C:\Users\root\Documents\GitHub\ezpkg\out\install\x64-Release" -DCMAKE_C_COMPILER:FILEPATH="C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.26.28801/bin/HostX64/x64/cl.exe" -DCMAKE_CXX_COMPILER:FILEPATH="C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.26.28801/bin/HostX64/x64/cl.exe"  -DCMAKE_TOOLCHAIN_FILE="C:/Users/root/Desktop/vcpkg/scripts/buildsystems/vcpkg.cmake" -DCMAKE_BUILD_TYPE="Release" -DCMAKE_MAKE_PROGRAM="c:\program files (x86)\microsoft visual studio\2019\community\common7\ide\commonextensions\microsoft\cmake\Ninja\ninja.exe" "C:\Users\root\Documents\GitHub\ezpkg" 2>&1"```

Is that of Visual Studio, can't seem to find the CLion command, they are throwing the same error so I suppose the difference isn't the IDEs fault anyway.

**Comment by marzer** [comment]
Nah, that looks like the invocation of cmake. I'm looking for the invocation of `cl.exe` (msvc), and the arguments passed to that. My suspicion is that it's being invoked as C++14, which is the default if no override is provided. For C++17 it's `/std:c++17`, and for C++20 (well, as much as is implemented anyway) it's `/std:c++latest`, currently.

The reason I'm thinking this is that those syntax errors look a lot like the ones you get when MSVC doesn't understand C++17's nested-namespace definitions in C++14 mode.

**Comment by marzer** [comment]
Alternatively you could try lowering `CMAKE_CXX_STANDARD` to 17 (since I assume that will work correctly for MSVC), just to see if you get different result.

**Comment by okureta** [comment]
A quick stackoverflow and. 
![image](https://user-images.githubusercontent.com/29059450/85210928-21851180-b33c-11ea-84d2-1658703d7ded.png)

😓

**Comment by marzer** [comment]
Hah, classic CMake.

**Comment by okureta** [comment]
Ah well, thank you for the quick replies. I'll be closing it now, thanks for the great library and I apologise for the inconveniences 🤗

**Comment by okureta** [comment]
Oh gosh, this is embarrassing, I sort of jumped to a conclusion and this does appear to be a different issue. If you build on a lower standard (e.g 11/14), then it throws **this** 
![image](https://user-images.githubusercontent.com/29059450/85211120-c7854b80-b33d-11ea-8a23-5a50a782edd0.png) error.

When changing it to C++17, it throws said errors.
![image](https://user-images.githubusercontent.com/29059450/85211134-e552b080-b33d-11ea-8e54-ab0e864a3512.png)

Very sorry, for closing it prematurely, I thought I had found a solution.

**Comment by marzer** [comment]
Ah well.

You said you're using exceptions (`/EHsc`), but those messages indicate otherwise (the warning in `<vector>`, and toml++ is using the internal `noex` ABI namespace). If you are meant to be using exceptions, try setting `TOML_EXCEPTIONS` to `1` before including toml.hpp, e.g.:

```cpp
#define TOML_EXCEPTIONS 1
#include <toml++/toml.hpp>
```

**Comment by okureta** [comment]
I have fixed the exceptions not being enabled issue, and defined TOML_EXCEPTIONS 1. The issue persists.
![image](https://user-images.githubusercontent.com/29059450/85211370-58f5bd00-b340-11ea-8e10-4287d6e820e9.png)

**Comment by marzer** [comment]
Ohhhhh. It's `std::numeric_limits::max()` getting nuked by a `max` macro. I'll fix it library-side, give me a few minutes.

**Comment by okureta** [comment]
I'll let you know the results once it's been pushed 😀👍

**Comment by marzer** [comment]
You can test it locally; change toml.hpp line 1426 to this:

```cpp
if (result > static_cast<uint64_t>((std::numeric_limits<int64_t>::max)()) + (sign < 0 ? 1ull : 0ull))
```

(I added an extra set of parens around `std::numeric_limits<int64_t>::max`)

**Comment by okureta** [comment]
Er?
![image](https://user-images.githubusercontent.com/29059450/85211531-1df48900-b342-11ea-9650-08935367b437.png)

**Comment by marzer** [comment]
Oh, wow. Where the fuck did I get 1426 from?? Line `8103` was the one, lol.

Doesn't matter now, I've pushed the fix.

**Comment by okureta** [comment]
Yeah, I found it myself and fixed it just as I saw your new comment 🤣 Everything works all good now 👍 Thanks!

**Comment by marzer** [comment]
:D Hooray!

**Comment by marzer** [comment]
Side note: If you changed your compiler to enable exceptions properly, you shouldn't _need_ to explicitly set `TOML_EXCEPTIONS` yourself, since the default behavior is to match whatever your compiler is set to. I only suggested that as a brute-force. It won't do you any harm to leave it set explicitly, though. That option is always going to be there.

**Comment by okureta** [comment]
Okay thanks! I have exceptions enabled properly now so I'll remove it.
