### ISSUE TITLE
Add support for std::wstring

### ISSUE THREAD

**Issue by levicki** [marzer/tomlplusplus#42]
Replace the _italic_ text below with the relevant information to help me understand your request.

**Is your feature request related to a problem? Please describe.**
_Currently if you want to pass `wchar_t *` or `std::wstring` as either key name or a string value, or read into `std::wstring` you must do the conversion to and from UTF-8 explicitly. This makes the library rather hard to use with Windows API, especially with DirectShow, DirectX, DirectWrite, Direct2D and other COM-based Win32 interfaces, including all OS API ending with `W`. Use of ANSI API is definitely discouraged nowadays so the only option at the moment is to do the necessary conversions yourself._

**Describe the solution you'd like**
_I would appreciate if your library would natively support `std::wstring` for value keys, file paths, string serialization/deserialization, doing all the wide string to UTF-8 (and vice versa) conversions in the background as needed._

**Describe alternatives you've considered**
_I don't see any good alternatives to native support for `std::wstring`._

**Additional context**
_N/A_

**Comment by marzer** [comment]
This is implemented now in master, insofar as I think I've covered all cases that make sense.

### Things that will now support wide strings on Windows:
- All table key lookup functions (`get`, `find`, `contains`, `operator[]`, ...)
- All table insertion/mutation functions (`insert`, `emplace`, `insert_or_assign`, `erase`, ...)
- All array insertion functions (`push_back`, `emplace_back`, `insert`, ...)
- Table constructors (e.g. `toml::table tbl{{ { L"key", L"val" } }};`)
- Array constructors (e.g. `toml::array arr{ L"val1", L"val2" };`)
- Value getters (e.g. `node.value_or(L"")`, `node.value<std::wstring>()`
- Node view comparisons, e.g. `tbl[L"key"] == L"val"`
- `parse_file(L"C:\\this\\is\\a\\wide\\string")`
- `parse(/* blah */, L"C:\\this\\is\\a\\wide\\string")`
- `source_region::wide_path()`

### Things that explicitly do not, and will not, support wide strings:
- Parsing a TOML document directly from a wide string or wide-character stream.
    - TOML spec mandates that a TOML document is valid UTF-8. If ever a TOML document is read from a non utf-8 source it's already out-of-spec and I don't want to increase the bug reporting surface area of the library to include that.
- Value getters returning `std::wstring_view`
    - The underlying storage of string values is still utf8 so in these cases there's nothing to view without introducing a bunch of undefined behavior. Getters that ordinarily can return a `std::string_view` are limited to a fully-fledged `std::wstring` in the wide-string case.

I think I've covered all the useful bits, though the API surface area that this impacts is pretty large so it's not going to be surprising if I've missed something. Feel free to re-open this if I have.

**Comment by levicki** [comment]
```
	void Deserialize(const toml::table& TOML)
	{
		for (auto&& [Key, Value] : TOML) {
				// Key is here char, .str() returns std::string_view
		}
	}
```
When I define `TOML_ENABLE_WINDOWS_COMPAT` it adds constructors that accept `std::wstring` but not the appropriate `.wstr()` method.
