### ISSUE TITLE
Allow serialization of literal strings using single quotes

### ISSUE THREAD

**Issue by levicki** [marzer/tomlplusplus#43]
Replace the _italic_ text below with the relevant information to help me understand your request.

**Is your feature request related to a problem? Please describe.**
_Currently it is not possible to serialize say a system path such as `C:\Path\To\Some\File.txt` into [literal TOML string](https://toml.io/en/). Instead, the strings are escaped and put in double quotes which makes them hard for humans to read and edit which is countering the main advantage of using TOML in the first place._

**Describe the solution you'd like**
_Make it possible to output raw, unescaped, strings with single quotes._

**Describe alternatives you've considered**
_I don't see any alternative to supporting one of the crucial TOML features._

**Additional context**
_N/A_

**Comment by marzer** [comment]
This is implemented now in master. The new behavior doesn't require any additional work on your part, the library will automatically try to use the 'most literal' form of string it can to emit the output in a round-trippable way. As long as your strings don't contain non-whitespace control characters they should use the `literal = 'form'`.

**Comment by marzer** [comment]
CC @bobfang1992 - you may want this!

**Comment by levicki** [comment]
@marzer Thanks for implementing this. It works just fine for my purpose (storing paths and USB device identifiers):

```
Camera = '\\?\usb#vid_0603&pid_8122&mi_00#7&1316d950&0&0000#{65e8773d-8f56-11d0-a3b9-00a0c9223196}\global'
CapturePath = 'C:\Camera'
```
