### ISSUE TITLE
More beginner/entry-level documentation

### ISSUE THREAD

**Issue by marzer** [marzer/tomlplusplus#47]
I've recently come to realize that the 'one-size-fits-all' mega-snippets on [marzer.github.io/tomlplusplus](https://marzer.github.io/tomlplusplus/) aren't necessarily useful for everyone, and I should break them up into smaller sub-examples. I'd be totally happy to accept help with this, though that may be wishful thinking!

**Comment by aprotyas** [comment]
@marzer what kind of sub-examples are you thinking of?

**Comment by marzer** [comment]
Good question. I think just itemizing some of the various steps in a more detailed or less dense way is the direction I'd like to go.

A good example is the [Working with TOML data](https://marzer.github.io/tomlplusplus/#mainpage-example-manipulations) section; it's the sort of code snippet that I personally find really helpful, but it's super dense and I have no doubt it's not to everyone's taste.
