### ISSUE TITLE
TOML serialization to ofstream and newline behavior

### ISSUE THREAD

**Issue by levicki** [marzer/tomlplusplus#48]
## Environment
**Compiler:**  
_Visual Studio 2019 16.6.3_

**C++ standard mode (e.g. 17, 20, 'latest'):**  
_C++17_

**Target arch (e.g. x64):**  
_x86_

**Exceptions enabled:**  
_Yes_

**Relevant `toml++` configuration customizations:**  
_TOML_EXCEPTIONS=0_

**Relevant compilation flags:**  
_N/A_

## Describe the bug
_When serializing TOML to a `std::ofstream` an extraneous newline is always inserted at the start of file even if it wasn't there, and a newline is always missing at the last line of the file._

I trust it you won't need a code sample or steps to reproduce for this one.

Lack of last newline can be solved by `myfile << endl;` after serialization but removing the empty one at the start is not possible.

Note that any inserted table has proper newline added before it, but maybe there should be special case of alphabetically first table in the file not having a leading newline unless there are values that belong to the file scope before?

**Comment by marzer** [comment]
Ah, there's supposed to be a check that hadnles the newline at the beginning, but I did some refactoring in the formatter when I added the new string handling and I must have broken it. Should be pretty easy to take care of, thanks.

**Comment by marzer** [comment]
There you go @levicki. You should not get leading newlines when the TOML data begins with a table, and should now get a trailing newline always. Thanks for bringing this to me!

**Comment by levicki** [comment]
You Sir, are totally welcome 🙂
