### ISSUE TITLE
Copying nodes

### ISSUE THREAD

**Issue by whiterabbit963** [marzer/tomlplusplus#49]
**Is your feature request related to a problem? Please describe.**
I am currently in the process of replacing a json library with your toml library, and I have encountered this issue a couple times, where I needed to make a copy of a node. In the first case, I was able to do a move. In other cases, I need a copy.
Specifically, I have a table with one element that is an array. I want to be able to copy that array to a second element in that table.

Existing table:
[table]
foo = [1, 2, 3]

In pseudo-code:
auto *array = table.get("foo");
table["bar"] = *array;

**Describe the solution you'd like**
I am pretty that I can accomplish this by manually iterating over the elements in the toml::node.

**Describe alternatives you've considered**
I was surprised to find that copy constructors were deleted.

**Additional context**
Are there, or will there be any plans to include node copying in the future?

**Comment by bobfang1992** [comment]
Why `std::move` is not an option for you?

**Comment by whiterabbit963** [comment]
@bobfang1992 In my example, I want the final table to look like:
[table]
foo = [1, 2, 3]
bar = [1, 2, 3]

In this case, std::move would create undefined behavior, unless foo is properly erased from the table.

I believe I found a solution that seems to compile. toml::table::insert_or_assign()
Doing further testing to ensure it works.

**Comment by Reedbeta** [comment]
As it happens, I've just encountered this issue as well. In my case, I wanted to create a shadow copy of a table, so that I can detect changes potentially made by other code (so that I know when to save the file).

I can understand deleting the copy and assignment operators, since it could be expensive to accidentally copy a large table; but maybe there could be a `deep_copy` method available for when it's needed.

**Comment by whiterabbit963** [comment]
@Reedbeta I thought about something similar via a `clone()` (same idea as `deep_copy()`), but I really do think copy ctors and operator=() provide the simplest mechanics to understand and use.
In my previous example, doing the following feels simpler:
```
auto *array = table.get("foo");
table["bar"] = *array;
```
rather than
```
auto *array = table.get("foo");
table.insert_or_assign("bar", std::move(array->clone()));
```
Having the copy ctors won't prevent possible errors/optimizations like `void foo(toml::table t);` vs `void foo(const toml::table &t);`, but without them, one doesn't have the freedom to choose a particular implementation.

Since toml tends to be more focused on human readability, I would not expect files > 10MB to be common place. For that reason, copy performance should be less concerning than ease of use.

**Comment by Reedbeta** [comment]
@whiterabbit963 I think with a clone method it would just be:
```cpp
table["bar"] = array->clone();
```
That `=` is now a move assign since the return value of `clone()` is an rvalue. Or so I'm guessing, since I haven't tried it. 🙂

**Comment by whiterabbit963** [comment]
@Reedbeta Yes a good compiler would know. From what I remember of past experiences fighting with deleted copy ctors, that didn't work, but I am open to being wrong on this one.
To further complicate things, I believe I noticed the toml::table::operator[] returns a toml::node_view. Which is confusing because we have toml::node_view (obviously non-copyable), and toml::node (less obviously non-copyable).

**Comment by whiterabbit963** [comment]
I also noticed, that the operator[] does not function the same as the STL's map::operator[].
```
Remark
std::map::operator[]'s behaviour of default-constructing a value at a key if it didn't exist is a crazy bug factory so I've deliberately chosen not to emulate it. This is not an error.
```
I have come to expect this behavior, and it is forcing me to rewrite some code where it was simpler to utilize this expectation.

**Comment by marzer** [comment]
@whiterabbit963

> Are there, or will there be any plans to include node copying in the future?

The only reason the copy constructors are deleted is because I never needed them, and in general I prefer to explicitly prohibit accidental copies of things where the heap is involved. I have no problem with this functionality being enabled.

It's complicated a bit by the fact that a node is not a concrete type; `toml::node` is an abstract base class, so a copy constructor on `toml::node` couldn't work, but I could allow copying in other places in the library. Additionally I could enable copy constructors on the concrete subclasses `toml::value`, `toml::array` and `toml::table` so you could perform copying if you cast `toml::node` to one of it's specializations (see [toml::node::as()](https://marzer.github.io/tomlplusplus/classtoml_1_1node.html#aa818a12fc0212e5e416b38fcf103f899) and friends).

In a potential future version of the library (when I have the time to do a pretty significant chunk of work on it) I'd like to revisit this design and move from inheritance to composition (as discussed in #31), which would allow me to do away with that particular caveat, but alas, that won't be for a while.

> To further complicate things, I believe I noticed the toml::table::operator[] returns a toml::node_view. Which is confusing because we have toml::node_view (obviously non-copyable), and toml::node (less obviously non-copyable).

See above.

> I also noticed, that the operator[] does not function the same as the STL's map::operator[].
> I have come to expect this behavior, and it is forcing me to rewrite some code where it was simpler to utilize this expectation.

Well, that's unfortunate, but the current design is here to stay. The library is designed to be optimal for config querying (i.e. just reading a value), with ease of modifying/writing coming second. (also, as you point out, the behaviour is clearly documented; anyone being surprised by this has just not looked at the docs).

**Comment by marzer** [comment]
> I thought about something similar via a clone() (same idea as deep_copy()), but I really do think copy ctors and operator=() provide the simplest mechanics to understand and use.

I agree with this sentiment, incidentally. If I'm going to provide copying, it'll be via copy construction, since that's the idiomatic C++ way of doing it. Providing a `clone()` method or similar just feels very... 'Java'...

**Comment by marzer** [comment]
Thanks for the feedback @whiterabbit963 and @Reedbeta! I'll spend a little bit of time on this today and come up with a basic implementation for you to use, and then iterate on it later in the week if you have further feedback.

**Comment by marzer** [comment]
Alright, this is tentatively implemented, pending any feedback I get here.

- tables, values and arrays now allow copy-construction and copy-assignment
- table and array insertion methods (push_back, insert etc.) support copying nodes of any type
- table and array insertion methods also now allow insertion of `toml::node&` and `toml::node&&` directly, without requiring you to cast (they'll internally do a `visit()` and 'do the right thing' with a reference to the concrete type)

**Comment by whiterabbit963** [comment]
I tested the following. Most things work as expected. Had some trouble with `table::emplace()` and `node_view`.
```
toml::table t1;
t1.insert_or_assign("bar1", toml::array{1, 2, 3});
t1.insert_or_assign("foo1", *t1.get("bar1"));

t1["foo1"] = t1["bar1"]; // does nothing should this fail to compile?
//*t1["foo1"].node() = *t1["bar1"].node(); // compile failure; copying node_view would be a bad thing
toml::array *array1 = t1["foo1"].node()->as_array();
array1->push_back(4);

//t1.insert_or_assign("foo3", t1["foo1"]); // fails to compile; a little unexpected
t1.insert_or_assign("foo2", *t1["foo1"].node());
toml::array *array2 = t1["foo2"].node()->as_array();
array2->push_back("wrench");

toml::table t2 = t1;
//t2.emplace("bar", toml::array{6, 7}); // fails to compile? not sure what I did wrong
t2.insert_or_assign("bar2", toml::array{6, 7});
cout << t1 << endl << t2;
```
sample output
```
bar1 = [ 1, 2, 3 ]
foo1 = [ 1, 2, 3, 4 ]
foo2 = [ 1, 2, 3, 4, 'wrench' ]

bar1 = [ 1, 2, 3 ]
bar2 = [ 6, 7 ]
foo1 = [ 1, 2, 3, 4 ]
foo2 = [ 1, 2, 3, 4, 'wrench' ]
```

**Comment by marzer** [comment]
```
t1["foo1"] = t1["bar1"]; // does nothing should this fail to compile?
```
Hmmn. If that compiles, it probably shouldn't! Node views are just views; you can't use them on the LHS of an assignment at all.

```
//t1.insert_or_assign("foo3", t1["foo1"]); // fails to compile; a little unexpected
```
Hmmn, yeah. This is a bit tricky; `node_views` represent a node, but they can also represent nothing (i.e. tbl["foo"] where `tbl` doesn't contain element `foo` creates a 'null' `node_view`). This requires a bit of plumbing, but I could figure something out.


```
//t2.emplace("bar", toml::array{6, 7}); // fails to compile? not sure what I did wrong
```
You didn't do anything wrong; that should work fine. I've likely fucked up somewhere.


Thanks for testing! Take your example here and build on it to improve what I have.

**Comment by marzer** [comment]
@whiterabbit963 Pushed implementation pass 2. Things should now work as you expect from your example, with the exception of this line:

```cpp
//t2.emplace("bar", toml::array{6, 7}); // fails to compile? not sure what I did wrong
```

I didn't realize when first replying, but that is actually the wrong way to call emplace(); because TOML data is homogeneous, you need to specify the emplacement type:

```cpp
t2.emplace<toml::array>("bar", 6, 7);
```

Which is effectively the same as:

```cpp
t2.insert("bar", toml::array{ 6, 7 });
```

Also, a fun FYI: I've enshrined your example in a unit test: https://github.com/marzer/tomlplusplus/blob/2efb15bf9ee1f2c238d8777d6c8ef8db1b04e2cb/tests/user_feedback.cpp#L10

**Comment by whiterabbit963** [comment]
Ok, that makes sense. The following also compiles.
```
t2.emplace<toml::array>("bar", toml::array{6, 7});
```
I am guessing the fact that it is both a node and an array, makes the type deduction ambiguous.

**Comment by marzer** [comment]
Yah, that'd be invoking the array's move constructor internally.

**Comment by whiterabbit963** [comment]
Oh fun with templates. These also work.
```
t2.emplace<toml::array>("bar", toml::array{6, 7}, toml::array{1, 2});
t2.emplace<toml::node>("bar", toml::array{6, 7}, toml::table{});
```
Also, as you pointed out, insert() takes two arguments a key and a value. emplace() takes a variable number of arguments to insert multiple items at once. The issue comes down to deducing the ValueType.

**Comment by marzer** [comment]
Oh well it's not an issue, it's by design. The function expects you to be explicit.

**Comment by marzer** [comment]
It's noted as such in the docs

**Comment by marzer** [comment]
Having said that, line 2 in that toy example shouldn't work... Guess that gives me something to dig into.

**Comment by whiterabbit963** [comment]
This should not work?
```
t2.emplace<toml::node>("bar", toml::array{6, 7}, toml::table{});
```

**Comment by whiterabbit963** [comment]
I pulled the latest, and that last example no longer compiles.

**Comment by marzer** [comment]
No that shouldn't work; nominally speaking it's saying "create an instance of toml:: node with these constructor arguments", but creating an instance of toml::node is impossible because it's abstract, so there's some type deduction happening that I didn't intend.

> As an aside, I am using qtcreator on windows to compile, and it uses Clang 6 or 7 (it will be v10 soon) to do type analysis checks

I test on Clang 7 - 11, GCC 7 - 10 and VS2019 before pushing the code to the remote, so I'll try that example myself and hopefully it'll make sense.. 

(I haven't been able to test with clang 6 because I can't get Catch2 to compile on it)

**Comment by whiterabbit963** [comment]
That makes sense. I wouldn't worry too much about it. That example fails to compile on my system (as it should).

**Comment by marzer** [comment]
Alright, well fair enough. I've still got a few more test cases to add for the new functionality, but let me know if you encounter some other unexpected behavior in the mean time.

**Comment by whiterabbit963** [comment]
Will do. I should have time to be able to investigate more later today.

**Comment by marzer** [comment]
Hmmn, I've just realized that the TOML source information contained by tables, arrays and values that are created by parsing will be copied into newly-constructed instances generated by the new functionality discussed in this thread:
```cpp
// TOML:
foo = 1

// C++:
auto tbl = toml::parse_file("config.toml");
std::cout << tbl["foo"].source() << "\n";

tbl.insert("bar", tbl["foo"]);
std::cout << tbl["bar"].source() << "\n";

// output:
line 1, column 6 of config.toml
line 1, column 6 of config.toml
```

I can't decide if this is 'correct' to be honest. It's reasonable to argue either way; it's not strictly correct for the new copy-constructed value (in that the new instance wasn't derived by parsing), but it _was_ copied directly and exactly from one that was... what do you think @whiterabbit963 (and/or anyone else who cares to chime in)?

**Comment by bobfang1992** [comment]
I am also leaning towards not copying these information as they are strictly linked to the original document but when we are using the copying constructor/assignment operators we are mostly likely manipulating the TOML objects to create a new document. Copying these does not make much sense to me.

**Comment by marzer** [comment]
> I am also leaning towards not copying these information as they are strictly linked to the original document [...] Copying these does not make much sense to me.

Yeah, that's pretty much my intuitive sense of it, though I figured I better sanity-check my reasoning.

**Comment by whiterabbit963** [comment]
I would argue for not copying as well.

**Comment by whiterabbit963** [comment]
Is there a source clear method? Would it make sense to nuke all source locations if a copy into a table occurs?

**Comment by marzer** [comment]
There's not, but it's easy to disable to copying without needing to add one.

**Comment by marzer** [comment]
Source information copying: disabled
Tests: added

Feel free to re-open this if you identify anything I've missed ^_^

**Comment by Reedbeta** [comment]
Neat, thanks for jumping on this so quickly Mark!

**Comment by marzer** [comment]
> Neat, thanks for jumping on this so quickly Mark!

Heh. Gotta do something while stuck inside on lockdown, right?

**Comment by ned14** [comment]
Just wanted to thank you for implementing table copying, I literally came here to report the need, and it was already done. Thanks!

**Comment by marzer** [comment]
No worries @ned14!
