### ISSUE TITLE
is_unicode_letter and is_unicode_number may be incomplete

### ISSUE THREAD

**Issue by Validark** [marzer/tomlplusplus#53]
**Related issue**: https://github.com/toml-lang/toml/issues/766

Presently, running https://gist.github.com/marzer/e7649c763cf4522686f85812f06022aa results in `letters` having 131230 codepoints in total, `numbers` having 886 codepoints in total, and `combining_marks` having 2282 codepoints in total. 

In contrast, `is_unicode_letter` says it only checks [131189](https://github.com/marzer/tomlplusplus/blob/ad6be8e51e28f6d3d78e3814e539684999bd7702/include/toml%2B%2B/toml_utf8.h#L486) and `is_unicode_number` only checks [876](https://github.com/marzer/tomlplusplus/blob/ad6be8e51e28f6d3d78e3814e539684999bd7702/include/toml%2B%2B/toml_utf8.h#L640). `is_unicode_combining_mark` says it checks [2282](https://github.com/marzer/tomlplusplus/blob/ad6be8e51e28f6d3d78e3814e539684999bd7702/include/toml%2B%2B/toml_utf8.h#L851) codepoints, which is all good!

Is there any way to get your python script to output C++ code in the format of your function?

**Comment by marzer** [comment]
Ah, that script is probably out-of-date; There was an off-by-one error IIRC. I've since moved all that logic to a different repository, you are welcome to have a look into it if you like: https://github.com/marzer/muu/blob/master/python/generate_unicode_functions.py

**Comment by marzer** [comment]
I will of course investigate myself, but I won't have time for a week or so.

**Comment by marzer** [comment]
If you do experiment with it, be forewarned that the first time you run it the entire Unicode database will be downloaded and some pre-processing is done on it, the results of which get cached locally as JSON dumps. It may take a few minutes to crunch through it all!

**Comment by Validark** [comment]
> It may take a few minutes to crunch through it all!

That sounds like a challenge to me!

------
In the old version of the script, `number` contains `[0-9]`, which `is_unicode_number` omits in favor of `is_decimal_digit`. That properly accounts for the difference of 10.

`letters` similarly contains A-Z and a-z, which contains 52 values (`is_ascii_letter` handles this in C++). That math on the hand... doesn't add up.... Your C++ is getting another 11 codepoints from somewhere, or it's the bug in the old script

**Comment by marzer** [comment]
Yeah, I'm fairly certain it's the old script that is wrong, though unfortunately the newer C++ generator script recently underwent a pretty big overhaul so I can't remember precisely where the issue was, since it was "lost in the noise", so to speak.

**Comment by marzer** [comment]
Ah! Found the bug. Indeed there was an off-by-one error in the old script, the current code is correct.

Here's the culprit: https://gist.github.com/marzer/e7649c763cf4522686f85812f06022aa#file-rangify_unicode_categories-py-L83

(the `for` loop on line 83 was supposed to iterate over `range(current_range_start, codepoint)`, but was originally iterating over `range(current_range_start, codepoint)`)
