### ISSUE TITLE
_Float16 is not present on g++

### ISSUE THREAD

**Issue by sobczyk** [marzer/tomlplusplus#57]
the _Float16 type is not present on arm g++

## Environment
g++ 7.4 7.5 and others

**C++ standard mode (e.g. 17, 20, 'latest'):**  
not applicable

**Target arch (e.g. x64):**  
arm64, arm

**Library configuration overrides:**  
not applicable

**Relevant compilation flags:**  
see steps to reproduce link

## Describe the bug
_Float16 is not available desptite gcc documentation saying one should use it
It's only available for C not C++

## Steps to reproduce (or a small repro code sample)
https://godbolt.org/z/5e6rdP
The last one shows it's visible for C

**Comment by marzer** [comment]
Is this causing a compiler error for you? I've been able to compile with float16 support on arm64.

**Comment by marzer** [comment]
> Is this causing a compiler error for you? 

Never mind, I've just tried compiling again on my arm64 tester and see the issue. Thanks, I'll look into this.

**Comment by bobfang1992** [comment]
Should this be included in CI? I mean multiple compiler and compiler versions etc.

**Comment by marzer** [comment]
Yeah, probably. The main reason it's not currently testing lots of compilers was to keep the Docker image small-ish.

I test lots of different compilers and configs on my own machine before committing, as well as testing on ARM64 using an rpi4:
- clang 6 - 11
- GCC 7 - 10
- vs 2019
- with/without exceptions
- C++17 and C++20

I'd like to migrate the CI to use GitHub actions and at that point I'd automate more platforms, but don't really have the time at the moment.
