### ISSUE TITLE
stream-operator prints superfluous newline at end

### ISSUE THREAD

**Issue by std-any-emplace** [marzer/tomlplusplus#68]
This is may be nitpicky, but adding a newline at the end - if wanted - is probably less a hassle than to remove it if unwanted.
```
{
  const auto data = R"(array=["v1", "v2", "v3"])"sv;
  auto table = toml::parse(data);	
  std::stringstream ss;
  ss << table;
  REQUIRE(ss.str() == "array = [ 'v1', 'v3' ]\n"sv); // NOTE extra newline at end
}
```

**Comment by marzer** [comment]
> This is may be nitpicky, but adding a newline at the end - if wanted - is probably less a hassle than to remove it if unwanted.

This is a good point; it would make more sense to give users the option.

**Comment by marzer** [comment]
Fixed in master, thanks @std-any-emplace!

@levicki this may impact you since #48 was your bug report; all it will mean is that if you want an explicit newline at the end of tables you'll need to add it yourself (which you did mention in your original report anyways).

**Comment by levicki** [comment]
@marzer At the end of all tables or just the last one?

**Comment by marzer** [comment]
@levicki Just the last one.

**Comment by marzer** [comment]
i.e.:

```cpp
std::cout << root_table;
```

would become

```cpp
std::cout << root_table << std::endl;
```

regardless of how many child tables were contained in `root_table`.
