### ISSUE TITLE
Failed to innclude as subproject using meson

### ISSUE THREAD

**Issue by jamabr** [marzer/tomlplusplus#72]
Dear Mark,

thanks for your nice lib! After sucessfully testing the implementation I started to add it as a submodule in meson and I experienced the issue below. There is a tiny problem with the `add_global_arguments` call in the context of a subproject. 

## Environment
**toml++ version and/or commit hash:**  

d95ff4c04f4d4a12f44dd8804f4f749c49abdff8

**Compiler:**  

g++

**C++ standard mode (e.g. 17, 20, 'latest'):**  
17

**Target arch (e.g. x64):**  
x64

**Library configuration overrides:**  

**Relevant compilation flags:**  

## Describe the bug
When trying to include the current version as subproject in the meson bulid system, meson fails with:

```
ERROR: Function 'add_global_arguments' cannot be used in subprojects because there is no way to make that reliable.
Please only call this if is_subproject() returns false. Alternatively, define a variable that
contains your language-specific arguments and add it to the appropriate *_args kwarg in each target.
```

## Steps to reproduce (or a small repro code sample)
Just inserted toml++ as a subproject in meson (0.54.2)
```
tomlpluspplus_proj = subproject('tomlplusplus')
tomlplusplus_dep = tomlpluspplus_proj.get_variable('tomlplusplus_dep')
```

## Additional information
Meson suggested fix successfully works, but I am not sure about the consequences. 
```
if compiler_supports_float128 and is_gcc
        if not is_subproject
               add_global_arguments('-fext-numeric-literals', language : 'cpp')
        endif
endif
```

Cheers,
Jan Martin

**Comment by marzer** [comment]
Ah, thanks for letting me know. To be honest I'm not sure if that part of the configuration is even necessary any longer; it was only ever meant to be used when compiling the tests. I'll try to refactor this out.

**Comment by jamabr** [comment]
Thanks for the quick reply. Great.

**Comment by marzer** [comment]
Fixed in master. Thanks @jamabr!

**Comment by jamabr** [comment]
Great, thanks for the quick action!
