### ISSUE TITLE
Are you interested in qbs Support?

### ISSUE THREAD

**Issue by HazardyKnusperkeks** [marzer/tomlplusplus#76]
**Is your feature request related to a problem? Please describe.**

This is more an inquiry than a feature request, but I want to use your library with the [qbs](https://doc.qt.io/qbs/) build system and I already do.
Are you interested in getting the qbs support, than I could try to make it more general and prepare a pull request.

**Describe the solution you'd like**

Getting an official `tomlplusplus.qbs`. :)

**Additional context**

**Comment by marzer** [comment]
Sure, the more ecosystems the library can slot into, the better! :)

**Comment by HazardyKnusperkeks** [comment]
Will work on it, but it have to wait until January.
