### ISSUE TITLE
Throwing on missing value or get full path to field from node object ?

### ISSUE THREAD

**Issue by lesurp** [marzer/tomlplusplus#78]
Hi, not sure if this is already doable and I'm just not finding it in the documentation, but my issue today was getting:

```
terminate called after throwing an instance of 'std::bad_optional_access'
  what():  bad optional access
[1]    69626 abort (core dumped)  ./build/foo
```

... and thinking "I wish I knew which mandatory key I forgot!"

From there, I was hoping there was an equivalent to `bar["baz"].value<unsigned int>();` that would return the value, or throw some error allowing me to pretty print which node could not be found (`std::vector<std::string>` for example?).

Afterwards, another solution I thought about was to write a short macro e.g.
```cpp
#define GET_NODE(n, t) \
[&n] { \
    try { \
        return n.value<t>.value(); \
    } catch (std::bad_optional_access) { \
        throw MyException("Missing parameter: {}", n.as_string(); \
    } \
}()
```

But getting the path from the node doesn't seem supported as far I can see :(

This feels like a rather simple problem though, is there already something for this use-case?
Thanks for the help and hard-work on the library!

**Comment by marzer** [comment]
Currently there's no built-in way to do this since the node_views don't keep track of their parent, but you could put together a helper function to do it with some variadic template magic. I just whipped this up and it seems to do what you need:

```cpp
template <typename DesiredValue, typename... Keys>
[[nodiscard]]
static DesiredValue get_fully_qualified_value_as(const toml::table& cfg, Keys&&... keys)
{
	using namespace std::string_view_literals;
	using namespace std::string_literals;
	using const_node_view = toml::node_view<const toml::node>;

	static constexpr auto build_key_string_elem = [](std::ostringstream& str, const auto& key, bool& prev_was_str)
	{
		using key_type = std::remove_cv_t<std::remove_reference_t<decltype(key)>>;
		static_assert(
			std::is_integral_v<key_type> || std::is_convertible_v<key_type, std::string_view>,
			"keys must be integers or strings"
		);

		if constexpr (std::is_integral_v<key_type>)
		{
			str << "["sv << static_cast<std::size_t>(key) << "]"sv;
			prev_was_str = false;
		}
		else
		{
			if (prev_was_str)
				str << "."sv;
			str << static_cast<std::string_view>(key);
			prev_was_str = true;
		}
	};

	static constexpr auto build_key_string = [&](const auto& ...keys_)
		-> std::string
	{
		bool prev_was_str = false;
		std::ostringstream oss;
		(build_key_string_elem(oss, keys_, prev_was_str), ...);
		return oss.str();
	};

	const_node_view nv{ cfg };
	((void)(nv = nv[keys]), ...);
	if (!nv)
		throw std::runtime_error{ "missing value: "s + build_key_string(keys...) };

	auto val = nv.value_exact<DesiredValue>();
	if (!val)
		throw std::runtime_error{ "value "s + build_key_string(keys...) + " was an unexpected type"s };

	return *val;
}

```

Example usage:
```cpp
const auto val = get_fully_qualified_value_as<int64_t>(tbl, "database", "ports", 2);
```

**Comment by lesurp** [comment]
Hey, thanks a lot, this indeed does what I was thinking about!

**Comment by marzer** [comment]
No worries, happy to help.

**Comment by marzer** [comment]
It never existed in the library. It's a helper function you might use yourself. The source is in the comment above.
