### ISSUE TITLE
The lib creates an empty table in an array of tables when parsing data if the data has an empty array of tables

### ISSUE THREAD

**Issue by marshevms** [marzer/tomlplusplus#81]
See https://github.com/marzer/tomlplusplus/pull/80

Some definitions [from](https://toml.io/en/v1.0.0-rc.3#array-of-tables):

> The last syntax that has not yet been described allows writing arrays of tables. These can be expressed by using a table name in double brackets. Under that, and until the next table or EOF are the key/values of that table. Each table with the same double bracketed name will be an element in the array of tables. The tables are inserted in the order encountered. A double bracketed table without any key/value pairs will be considered an empty table.

But for me and for the logic of this library, this **[[example]]** and this **example = []** is essentially the same, but in the first case, there will be an empty table inside. And the whole problem essentially comes down to visual representation. (Correct me if this is not the case I'm new to this format)

I see three ways:
1. My PR. But this is workaround and I just pointed out where the problem is.
2. The way suggested by [marzer](https://github.com/marzer). But I think this is workaround too. I not expert in lib, I think this can be problem to determine is the empty table creates by lib or just user do this.
3. Create new type **array_of_tables** or **tables_array**. Moreover, the library already has a function to determine whether a node is an array of tables

I think the third way is the best.

P.S. I didn't look at other libraries and don't know if this problem exists and how they solved it.

**Thanks for attention**

**Comment by marzer** [comment]
> But for me and for the logic of this library, this [[example]] and this example = [] is essentially the same

No, they are not the same. `[[example]]` and `example = [{}]` are conceptually the same (note the extra inner inline table), but `[[example]]` and `example = []` _are not_. An array of tables is _two_ things combined in one by virtue of syntactic sugar: it is an array that contains tables. Not an simply an array.

> I think the third way is the best.

I disagree. Some other libraries went this route but that just complicates their use because it forces you to special-case arrays-of-tables as distinct from arrays of anything else. It was actually one of the things that annoyed me about the C++ alternatives before I chose to write this library. I won't be doing that.

**Comment by marzer** [comment]
Also consider this line from the standard text you quoted above:

> A double bracketed table without any key/value pairs will be considered an empty table.

If I adopt the changes you want I'm no longer complying with this part of the TOML spec.

**Comment by marshevms** [comment]
> No, they are not the same. `[[example]]` and `example = [{}]` are conceptually the same (note the extra inner table), but `[[example]]` and `example = []` _are not_. An array of tables is _two_ things combined in one by virtue of syntactic sugar: it is an array that contains tables. Not an simply an array.

I said the same thing)

**Comment by marshevms** [comment]
For me it looks like a visual requirement for now, that's all. Thanks.

**Comment by marzer** [comment]
It's not just a visual thing at all. I think I've explained that pretty comprehensively...
