### ISSUE TITLE
Simplify use of array-of-values and array-of-tables

### ISSUE THREAD

**Issue by jenisys** [marzer/tomlplusplus#87]
**Is your feature request related to a problem? Please describe.**
Currently, the extraction of config data is unnecessary complicated for the following cases:

* array-of-values (`value_type=T` as homogeneous array)
* array-of-table

The necessary code requires to use `some_toml.as_array()`, `some_toml.as_table()` and nullptr checking.
This code is very repetitive and error-prone if you need to repeat it over and over again.
In addition, it hides the stuff what the user actually wants to do (neither compact nor very readable).

NOTES:

* Nothing of that is shown in the documentation where only simplistic cases without sane error handling is shown.
* array-of-values: The user has a config-schema in mind where all items have the same value_type=T
* Better support of native C++ types (`std::vector<T>`, ...) would improve things because that is in many the case the major use case.

SIMILAR: Issue #70

**Describe the solution you'd like**

EXAMPLE 1: Simplified extraction of config data from an array-of-tables
```toml
# -- FILE: example1.toml
[[library]]
name = "libone"

[[library]]
name = "libtwo"
```

```c++
// -- EXAMPLE: toml::array_of_tables_foreach
// toml::array_of_tables_foreach(const toml::table& config, std::string_view key, std::function<void(const toml::table&)>);
//   * Simplifies to extract data from each table of an array-of-tables.
//.  * Function implementation provides the boilerplate code to extract in type-safe way
//.  * Hides the complexity of xxx.as_array(), xxx.as_table() and nullptr checking from the user (and implements it once)
//.  * Makes the expected config-schema readable and compact
using Strings = std::vector<std::string>;
const toml::table config = toml::parse_file("example1.toml");

String libraryNames;
toml::array_of_tables_foreach(config, "library", [&](const toml::table& itemTable) {
   // -- FOREACH TABLE in array-of-tables: Extract table-data
    auto libraryName = itemTable["name"].value_or(std::string{});
    libraryNames.push_back(libraryName);
});
assert(libraryNames == Strings{"libone", "libtwo"});

// -- MAYBE: array-of-tables solved in a similar way like array-of-values (SEE: EXAMPLE 2)
// HINT: Auto-use empty array if parameter does not exist.
for (const toml::table& itemTable : toml::get_array_of_tables(config, "library")) {
   ... // Extract the table data
}
// OR:
for (const toml::table& itemTable : config["library"].as_array_of_tables()) {
   ... // Extract the table data
}
```

EXAMPLE 2: Simplified extraction of config data from an array-of-values
```toml
# -- FILE: example2.toml
numbers = [ 1, 2, 4 ]
```

```c++
// -- EXAMPLE:  as_array_of<T>()
//  CASE 1: Returns std::optional< std::vector<T> >
//. CASE 2: Returns std::vector<T> if all items match value_type=T. -- not shown here
using Numbers = std::vector<int>;
const toml::table config = toml::parse_file("example2.toml");
Numbers numbers = config["numbers"].as_array_of<int>().value_or({});
assert(numbers == Numbers{ 1, 2, 4});

// -- ALTERNATIVE: As helper function with std::optional< std::vector<T> >
Numbers numbers = toml::get_array_of<int>(config, "numbers").value_or({});
```

**Additional context**

* Error handling if config-schema is violated (non-homogeneous array-of-values if homegeneous array-of-values is expected). Maybe additional function variants with an additional parameter `faultHandler` could handle this.
* Fault: TOML parameter is missing -- Should be handled by std::optional

**Comment by marzer** [comment]
Yah there's an opportunity to simplify things a bit here, since arrays-of-tables are a somewhat annoying edge case. Some helper functions are probably the right way to go here, but I won't have time to implement this in the near future. I'd welcome a PR!
