### ISSUE TITLE
Allow parse_file to create file if it doesn't exist

### ISSUE THREAD

**Issue by BluTree** [marzer/tomlplusplus#90]
**Is your feature request related to a problem? Please describe.**
When trying to parse a file that doesn't exist, the lib throw an error. But for something like settings file, there are many times the settings are created at the first launch of a program.

**Describe the solution you'd like**
A possible solution could be to add a boolean (by default false) to create the file instead of throwing an error when parsing it.
Another possibility could be another function, something like `parse_or_create_file(const char* path)`, that will create the file if the lib cannot open it.

**Additional context**

**Comment by marzer** [comment]
There's likely to be many opinions on what the appropriate semantics are here. Is creating an empty file on disk OK? If not, how does the callsite specify the default TOML? What should the function return? Etc.

Given that, I would rather not try to answer those questions at all. A simpler solution is for you to create a helper function in your own code that handles the situation exactly as you need it handled.
