### ISSUE TITLE
Add convenience methods that throw more exceptions when accessing missing keys/wrong types

### ISSUE THREAD

**Issue by gsauthof** [marzer/tomlplusplus#91]
**Is your feature request related to a problem? Please describe.**

Recently I end up writing some toml code pieces that looks like this:

```
        const toml::table *tblP = pkt.as_table();
        if (!tblP)
            throw std::runtime_error("flow element is not a table");

        const toml::table &tbl = *tblP;

        if (auto v = tbl["pkt"]) {
            if (auto w = v.value<std::string_view>())
                parse_packet(w.value(), p);
            else
                throw std::runtime_error("pkt not a string type");
        } else {
            throw std::runtime_error("pkt key missing in flow packet");
        }
```
That means I'll have to add a lot of mechanical error handling code which is tedious and error prone. Even with such extra code it's hard to present the user useful error messages, e.g. ones with line/column numbers.

Instead I would prefer if the toml library would do all that error checking/reporting for me, e.g. like this:

**Describe the solution you'd like**

```
        const toml::table &tbl = pkt.as_table_or_fail();
        // => if it fails then the toml exception would include line number, an element path,
        //      the expected and actual types

        parse_packet(tbl.get_or_fail("pkt").value_or_fail<std::string>());
        // => again, this might throw descriptive exceptions for several possible failure:
        // 1. key is missing
        // 2. key has wrong type
        // again with some context information
```

**Additional context**

**Comment by marzer** [comment]
Thanks for the suggestion. I might add something like this long-term, but at the moment my attention is focused elsewhere and I'm only really applying bugfixes. That being said, all the information you need to do this is already in the library; in the short-term you might consider implementing this as a helper function in your own codebase - the code I posted in [this issue](https://github.com/marzer/tomlplusplus/issues/78) is probably a good start.

(I'd of course welcome a PR to add something like this).
