### ISSUE TITLE
A lot of warnings are issued when compiling under MSVC

### ISSUE THREAD

**Issue by Atari2** [marzer/tomlplusplus#94]
## Environment
toml++ v2.3.1
MSVC 19.28.29914.0
C++17
x86
Compiling with /Wall /MT

## Describe the bug
I'm working on a project that just parses a TOML file to get some configuration values, nothing special going on. I'll attach some code in the section below which shows just what's the amount of warnings that you get from a simple short code. 
The short code below produces a total of 77 warnings, my project leads to 390 warnings.
Compiling on Visual Studio 2019 with MSVC with /Wall lends an incredible amount of super noisy warnings, it is of note that absolutely 0 warnings appear on either GCC 10.2 or Clang 11 (both using very high warning level, `-Wall -Wpedantic -Wextra`).
Major offenders include (in order of how many times they appear):

- [C4946](https://docs.microsoft.com/en-US/cpp/error-messages/compiler-warnings/compiler-warning-level-1-c4946?view=msvc-160) (by far the worst offender, 53 times in the small code, 339 times in my code)
- [C4866](https://docs.microsoft.com/en-us/cpp/error-messages/compiler-warnings/c4866?view=msvc-160) (2 times in the small code, 26 times in my code)
- [C6001](https://docs.microsoft.com/en-us/cpp/code-quality/c6001?view=msvc-160) (4 times in both code pieces)
- [C26495](https://docs.microsoft.com/en-us/cpp/code-quality/c26495?view=msvc-160) (3 times in both code pieces)
- [C26451](https://docs.microsoft.com/en-us/cpp/code-quality/c26451?view=msvc-160) (4 times in both code pieces)
- [C6262](https://docs.microsoft.com/en-us/cpp/code-quality/c6262?view=msvc-160) (1 time in both, this may be more important than others, since Windows tends to have easy stack problems due to the [their minimal stack size (1 MB)](https://docs.microsoft.com/en-us/windows/win32/procthread/thread-stack-size) compared to unix (often even 8MB of virtual size).

## Steps to reproduce (or a small repro code sample)
```cpp
#include <fstream>
#include <array>
#include <string>
#include "toml/toml.hpp"

int main(int argc, char* argv[]) {
	std::array<std::string, 2> b{ "hello", "world" };
	auto tbl = toml::parse_file("test.toml");
	auto paths_ptr = tbl["test"].as_table();
	if (paths_ptr != nullptr) {
		auto& val = *paths_ptr;
		b[0] = val["hello"].value_or(b[0]);
	}
        return 0;
}
```
^^^ this code gives 77 warnings.

## Additional information
I don't know if you'll want to do something about this but I figured I'd at least let you know, since some of those warnings may actually be of importance. Also it effectively renders compiling with /Wall almost impossible because you receive a lot of noise.
Sidenote: I believe that `bug` is the wrong tag for this issue, but this was not a feature request either, and bug was the more "fitting" one, feel free to change it to whatever you most please.

**Comment by marzer** [comment]
Thanks for the report! I've pushed a fix in master. Most were false positives (all the switch ones), though the stack size one was good. My stack buffer was way too big.

Only one that I'm a bit confused about is [C4866](https://docs.microsoft.com/en-us/cpp/error-messages/compiler-warnings/c4866?view=msvc-160); it seems as though it's only a concern if the operator would have side effects, but since this one doesn't... ¯\\\_(ツ)\_/¯
