### ISSUE TITLE
Many errors when using Meson subproject

### ISSUE THREAD

**Issue by tudou** [marzer/tomlplusplus#97]
Hey,

this is my first time using Meson and I was trying to integrate toml++ into my project using the build systems subproject feature,
I successfully include it.

![image](https://user-images.githubusercontent.com/76058207/117547971-49e82e00-b02a-11eb-903f-b18d00616a10.png)

However, at build time, I get an abundant amount of errors of which I cannot find a solution to. Builds run perfectly fine through CMake and using target_include_directories.

![image](https://user-images.githubusercontent.com/76058207/117547851-bdd60680-b029-11eb-8188-87a415bb1e0a.png)

Apologies if this was documented somewhere and this is the fault of my stupidity. Thank you for the library.

**Comment by marzer** [comment]
Hey, thanks for the report! Can you post the full build output as a text dump?

**Comment by tudou** [comment]
Hi,

I've made some changes since I no longer receive this error.
It seemed to have to been something to do with the cache or something as after I hard reset Meson it started working.

Apologies for not answering sooner, great library btw.

![image](https://user-images.githubusercontent.com/76058207/117548615-d811e380-b02d-11eb-88b4-bd3d5389ac45.png)
